### ISSUE TITLE
Error: Precomputed metric requires shape ""(n_queries, n_indexed). Got (%d, %d) "for %d indexed."

### ISSUE THREAD

**Issue by DashengSong** [sebp/scikit-survival#109]
Hi, I tried to build minlipsurvival model . After i have tuned parameters and use it to predict new test data, i encountered a error：“Precomputed metric requires shape ""(n_queries, n_indexed). Got (290, 290) "for 1157 indexed."
my train data shape is （1157，19），test data shape is （290，19）

**Comment by sebp** [comment]
When using a precomputed metric, you need to pass in a Kernel matrix 
when fitting/predicting. For testing the Kernel matrix must have shape 
(n_samples_test, n_samples_train).
