### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by paulamartingonzalez** [sebp/scikit-survival#111]
Thanks for your great work! When trying to work in Google Colab with Scikit-Survival, I get the following error:

> /usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
>     790                 # Oops, the "best" so far conflicts with a dependency
>     791                 dependent_req = required_by[req]
> --> 792                 raise VersionConflict(dist, req).with_context(dependent_req)
>     793 
>     794             # push the new requirements onto the stack
> 
> ContextualVersionConflict: (osqp 0.6.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('osqp!=0.6.0,!=0.6.1'), {'scikit-survival'})

Any chances requirements could be made more flexible?

**Comment by sebp** [comment]
Unfortunately not, see https://github.com/sebp/scikit-survival/pull/98

But version osqp 0.5.0 should work fine, unless that version is excluded 
by another package your are using.
