### ISSUE TITLE
Get kernel matrix

### ISSUE THREAD

**Issue by paulamartingonzalez** [sebp/scikit-survival#112]
Is it possible to get the pairwise kernel from FastKernelSurvivalSVM?

I am trying it with:

> estimator = FastKernelSurvivalSVM(alpha =1000,optimizer="rbtree",kernel='rbf',gamma=0.01,max_iter=1000, tol=1e-6, random_state=0)
> K_rbf = estimator._get_kernel(data_x_numeric, data_y)

and I am getting the following error:

> /usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
>      83 
>      84     """
> ---> 85     return array(a, dtype, copy=False, order=order)
>      86 
>      87 
> 
> TypeError: Cannot cast array data from dtype([('censored', '?'), ('time', '<f8')]) to dtype('float64') according to the rule 'unsafe'

Should I maybe change the y format? I am using the one defined in your docs.

**Comment by sebp** [comment]
You can just use sklearn via the sklearn.metrics.pairwise.rbf_kernel 
function

**Comment by paulamartingonzalez** [comment]
Thanks @sebp for the quick reply! I already tried, but the data_y format seems to give me problems too as I get the exact same error (copied below). Any idea of how I can give it the desired format? I assume this has been solved elsewhere as the FastKernelSurvivalSVM works great with GridSearchCV trying different kernels.

>       1 **from sklearn.metrics.pairwise import pairwise_kernels**
> ----> 2 **K_rbf = pairwise_kernels(data_x_numeric, data, metric=estimator.kernel, filter_params=True,  {"gamma": 0.01,"alpha":1000})**
> 
> 5 frames
> /usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
>      83 
>      84     """
> ---> 85     return array(a, dtype, copy=False, order=order)
>      86 
>      87 
> 
> TypeError: Cannot cast array data from dtype([('censored', '?'), ('time', '<f8')]) to dtype('float64') according to the rule 'unsafe'

**Comment by sebp** [comment]
Note that the second argument is another feature matrix and used if you 
want to compute a non-symmetric Kernel matrix (e.g. the kernel between 
train and test data). You do not use survival information to compute the 
Kernel matrix. See 
https://scikit-learn.org/stable/modules/svm.html#using-python-functions-as-kernels
