### ISSUE TITLE
OneHotEncoder select which to drop

### ISSUE THREAD

**Issue by chanshing** [sebp/scikit-survival#113]
First, thanks for your awesome package.

Question: Is there a way to select which category value to drop in `OneHotEncoder`? For example, if we have `treatment` taking values `A, B, C`, is there a way to drop B so that we get `treatment=A` and `treatment=C`?

**Comment by sebp** [comment]
That's currently not possible. Have a look at patsy, it offers more options to convert categorical variables to numeric. If you ask it to return a DataFrame, you can use the result with scikit-survival.
