### ISSUE TITLE
Scikit-survival broken config in pyfi

### ISSUE THREAD

**Issue by juliedrew** [sebp/scikit-survival#114]
Hi Sebastian,
 
Thanks for building the package scikit-survival and your contributions to the community.

I am a Research Scientist at Facebook. I am trying to install this package using pyfi and I get the following error:
ModuleNotFoundError: No module named 'numpy'
Building wheel for scikit-survival (setup.py): finished with status 'error'

One of the production engineers who is helping me with installation told me the following:

This package has a broken config. It should specify numpy as a build-time dependency but it does not; we (as well as pypi.org) can't even figure out the dependency chain in this case.

Evidence: requires_dist is null at https://pypi.org/pypi/scikit-survival/json

One solution is to upload a wheel, which I think will update the metadata we need to know numpy is involved, at which point we already install as if it was a build-time dep because this class of issue is so common.

 It would be great if you can upload a new wheel with the appropriate config.
Thanks a lot for your help!

**Comment by sebp** [comment]
I recently updated the build system to be compatible with PEP-517/518, 
which should fix this issue. The changes are currently only available in 
master. You can ask pip to install from there:

pip install git+https://github.com/sebp/scikit-survival.git


It would be great if you could give a try and let me know whether the 
new build system indeed fixes your issue.

**Comment by thatch** [comment]
Yes, the pep 517 build from master works great.  Thanks.
