### ISSUE TITLE
Coefficients of the model(CoxPHSurvivalAnalysis()) are non-zero, but identical CHF occur for non-identical feature vectors

### ISSUE THREAD

**Issue by SurajitTest** [sebp/scikit-survival#118]
Hi Sebastian,

What I am saying is the fact that all coefficients of the model(CoxPHSurvivalAnalysis()) are non-zero, but identical CHF occur for non-identical feature vectors - Please consider the given below data.  I am also observing the same behaviour for CoxnetSurvivalAnalysis().

Is there any specific reason for what I am observing that OR am I  missing something ? Appreciate your thoughts and inputs.

Data of Censored Objects of the Train Set (Features are not the same)

    Karnofsky_score  Months_from_Diagnosis  Prior_therapy=yes  Treatment=test  
                            8              50.0                   18.0                0.0             0.0  
                            12             30.0                    4.0                0.0             0.0  
                            24             80.0                    3.0                0.0             0.0  
                            80             20.0                   36.0                0.0             1.0  

The coefficients of the model are given below(Model coefficients are not zero):

Age_in_years            -0.010250
Celltype=large          -0.737747
Celltype=smallcell      -0.338654
Celltype=squamous       -1.228854
Karnofsky_score         -0.031113
Months_from_Diagnosis   -0.002255
Prior_therapy=yes        0.060748
Treatment=test           0.386417

The content of Time Array and CHF values for the 4 Censored Objects of the Train Set is given below (array y is same for all the 4 censored objects of the Train Data Set):

Iteration 1
The array x is <class 'numpy.ndarray'> of shape (81,) and contains [  1.   2.   3.   4.   7.   8.  11.  12.  13.  15.  16.  18.  19.  20.
  21.  22.  24.  25.  29.  30.  31.  33.  35.  36.  42.  43.  45.  48.
  49.  51.  52.  53.  54.  59.  61.  63.  73.  82.  83.  84.  87.  92.
  95.  99. 100. 103. 110. 111. 112. 117. 118. 122. 123. 126. 133. 139.
 140. 143. 144. 151. 153. 156. 162. 164. 177. 182. 200. 201. 231. 260.
 278. 314. 340. 357. 384. 389. 392. 553. 587. 991. 999.] :

The array y is <class 'numpy.ndarray'> of shape (81,) and contains [  0.22888716   0.34577644   0.46530054   0.58852671   0.83939303
   1.10744289   1.24777949   1.52928268   1.81841601   2.11970163
   2.27516181   2.59459553   2.76493976   3.11735835   3.30654435
   3.50026028   3.69603929   4.10590787   4.3188861    4.75883573
   5.20702024   5.43712483   5.67191329   5.91530441   6.16399916
   6.41390886   6.6681559    6.93657102   7.24334203   7.89445818
   8.25734006   8.62940198   9.38873821   9.77925883  10.19292985
  10.61661439  11.05704044  11.51995335  11.51995335  12.00081407
  12.4979616   13.02359187  13.56630362  14.69043228  14.69043228
  15.2900743   15.93192193  17.22502122  17.90753575  19.29055973
  20.02939867  20.77799957  20.77799957  21.62009675  22.48008237
  23.36673272  24.27807438  25.26771492  26.27271     27.34194912
  28.50061146  29.74504882  32.32183708  33.72477319  35.21286973
  35.21286973  36.86828738  38.60104499  40.39899066  42.57484861
  44.87450645  47.3926523   50.1785393   53.2323139   56.55105099
  60.87809     65.48006933  74.10467789  86.20583522 107.88040887
 172.10443502] :

Iteration 2
The array x is <class 'numpy.ndarray'> of shape (81,) and contains [  1.   2.   3.   4.   7.   8.  11.  12.  13.  15.  16.  18.  19.  20.
  21.  22.  24.  25.  29.  30.  31.  33.  35.  36.  42.  43.  45.  48.
  49.  51.  52.  53.  54.  59.  61.  63.  73.  82.  83.  84.  87.  92.
  95.  99. 100. 103. 110. 111. 112. 117. 118. 122. 123. 126. 133. 139.
 140. 143. 144. 151. 153. 156. 162. 164. 177. 182. 200. 201. 231. 260.
 278. 314. 340. 357. 384. 389. 392. 553. 587. 991. 999.] :

The array y is <class 'numpy.ndarray'> of shape (81,) and contains [  0.22888716   0.34577644   0.46530054   0.58852671   0.83939303
   1.10744289   1.24777949   1.52928268   1.81841601   2.11970163
   2.27516181   2.59459553   2.76493976   3.11735835   3.30654435
   3.50026028   3.69603929   4.10590787   4.3188861    4.75883573
   5.20702024   5.43712483   5.67191329   5.91530441   6.16399916
   6.41390886   6.6681559    6.93657102   7.24334203   7.89445818
   8.25734006   8.62940198   9.38873821   9.77925883  10.19292985
  10.61661439  11.05704044  11.51995335  11.51995335  12.00081407
  12.4979616   13.02359187  13.56630362  14.69043228  14.69043228
  15.2900743   15.93192193  17.22502122  17.90753575  19.29055973
  20.02939867  20.77799957  20.77799957  21.62009675  22.48008237
  23.36673272  24.27807438  25.26771492  26.27271     27.34194912
  28.50061146  29.74504882  32.32183708  33.72477319  35.21286973
  35.21286973  36.86828738  38.60104499  40.39899066  42.57484861
  44.87450645  47.3926523   50.1785393   53.2323139   56.55105099
  60.87809     65.48006933  74.10467789  86.20583522 107.88040887
 172.10443502] :

Iteration 3
The array x is <class 'numpy.ndarray'> of shape (81,) and contains [  1.   2.   3.   4.   7.   8.  11.  12.  13.  15.  16.  18.  19.  20.
  21.  22.  24.  25.  29.  30.  31.  33.  35.  36.  42.  43.  45.  48.
  49.  51.  52.  53.  54.  59.  61.  63.  73.  82.  83.  84.  87.  92.
  95.  99. 100. 103. 110. 111. 112. 117. 118. 122. 123. 126. 133. 139.
 140. 143. 144. 151. 153. 156. 162. 164. 177. 182. 200. 201. 231. 260.
 278. 314. 340. 357. 384. 389. 392. 553. 587. 991. 999.] :

The array y is <class 'numpy.ndarray'> of shape (81,) and contains [  0.22888716   0.34577644   0.46530054   0.58852671   0.83939303
   1.10744289   1.24777949   1.52928268   1.81841601   2.11970163
   2.27516181   2.59459553   2.76493976   3.11735835   3.30654435
   3.50026028   3.69603929   4.10590787   4.3188861    4.75883573
   5.20702024   5.43712483   5.67191329   5.91530441   6.16399916
   6.41390886   6.6681559    6.93657102   7.24334203   7.89445818
   8.25734006   8.62940198   9.38873821   9.77925883  10.19292985
  10.61661439  11.05704044  11.51995335  11.51995335  12.00081407
  12.4979616   13.02359187  13.56630362  14.69043228  14.69043228
  15.2900743   15.93192193  17.22502122  17.90753575  19.29055973
  20.02939867  20.77799957  20.77799957  21.62009675  22.48008237
  23.36673272  24.27807438  25.26771492  26.27271     27.34194912
  28.50061146  29.74504882  32.32183708  33.72477319  35.21286973
  35.21286973  36.86828738  38.60104499  40.39899066  42.57484861
  44.87450645  47.3926523   50.1785393   53.2323139   56.55105099
  60.87809     65.48006933  74.10467789  86.20583522 107.88040887
 172.10443502] :

Iteration 4
The array x is <class 'numpy.ndarray'> of shape (81,) and contains [  1.   2.   3.   4.   7.   8.  11.  12.  13.  15.  16.  18.  19.  20.
  21.  22.  24.  25.  29.  30.  31.  33.  35.  36.  42.  43.  45.  48.
  49.  51.  52.  53.  54.  59.  61.  63.  73.  82.  83.  84.  87.  92.
  95.  99. 100. 103. 110. 111. 112. 117. 118. 122. 123. 126. 133. 139.
 140. 143. 144. 151. 153. 156. 162. 164. 177. 182. 200. 201. 231. 260.
 278. 314. 340. 357. 384. 389. 392. 553. 587. 991. 999.] :

The array y is <class 'numpy.ndarray'> of shape (81,) and contains [  0.22888716   0.34577644   0.46530054   0.58852671   0.83939303
   1.10744289   1.24777949   1.52928268   1.81841601   2.11970163
   2.27516181   2.59459553   2.76493976   3.11735835   3.30654435
   3.50026028   3.69603929   4.10590787   4.3188861    4.75883573
   5.20702024   5.43712483   5.67191329   5.91530441   6.16399916
   6.41390886   6.6681559    6.93657102   7.24334203   7.89445818
   8.25734006   8.62940198   9.38873821   9.77925883  10.19292985
  10.61661439  11.05704044  11.51995335  11.51995335  12.00081407
  12.4979616   13.02359187  13.56630362  14.69043228  14.69043228
  15.2900743   15.93192193  17.22502122  17.90753575  19.29055973
  20.02939867  20.77799957  20.77799957  21.62009675  22.48008237
  23.36673272  24.27807438  25.26771492  26.27271     27.34194912
  28.50061146  29.74504882  32.32183708  33.72477319  35.21286973
  35.21286973  36.86828738  38.60104499  40.39899066  42.57484861
  44.87450645  47.3926523   50.1785393   53.2323139   56.55105099
  60.87809     65.48006933  74.10467789  86.20583522 107.88040887
 172.10443502] :

Thanks,
Surajit

**Comment by sebp** [comment]
There's somewhat of an inconsistency between CHF and survival functions. While for the latter, you can list plot `x` and `y` of the returned StepFunction, for CHF that is not case. In fact, in both cases, you should actually evaluate the StepFunction at `x`:

```python
import matplotlib.pyplot as plt    
from sksurv.datasets import load_veterans_lung_cancer    
from sksurv.preprocessing import OneHotEncoder    
from sksurv.linear_model import CoxPHSurvivalAnalysis    
    
X, y = load_veterans_lung_cancer()    
Xt = OneHotEncoder().fit_transform(X, y)    
    
est = CoxPHSurvivalAnalysis()    
est.fit(Xt, y)    
                                                                                                          
chf = est.predict_cumulative_hazard_function(Xt.iloc[:4, :])    
    
for f in chf:    
    # evaluate CHF    
    probs = [f(t) for t in f.x]    
    plt.step(f.x, probs, where="post")    
    
plt.show()
```

![chf](https://user-images.githubusercontent.com/74460/84590863-8666d600-ae29-11ea-95d9-ba67713106fd.png)

This should be clarified in the documentation as "Introduction to Survival Analysis with scikit-survival" notebook.

**Comment by SurajitTest** [comment]
Hi,

       Thanks for clarifying this out. The information that you did provide
is not part of the  "Introduction to Survival Analysis with
scikit-survival" notebook, as in this notebook , only survival function is
plotted and not the cumulative hazard function for CoxPH methods.

       Additionally, in the given below code snippet when I 'print(f.y)',
what do I see ? Asking this question as 4 array values are identical

chf = est.predict_cumulative_hazard_function(Xt.iloc[:4, :])

for f in chf:
    print(f.y)


Thanks
Surajit

**Comment by sebp** [comment]
y is the baseline CHF.
