### ISSUE TITLE
Error when using PIP to install scikit-survival 0.13 that uses PEP 517

### ISSUE THREAD

**Issue by SurajitTest** [sebp/scikit-survival#126]
**Describe the bug**

**Code Sample to Reproduce the Bug**

```python
# Insert your code here that produces the bug.
# This example should be as succinct as possible and self-contained,
# i.e., not rely on external data.
# We are going to copy-paste your code and we expect to get the same result as you.
# It should run in a fresh python session, and so include all relevant imports.
```

**Expected Results**

**Actual Results**
Please paste or specifically describe the actual output or traceback.

**Versions**
Please execute the following snippet and paste the output below.

```python
import sklearn; sklearn.show_versions()
import sksurv; print("sksurv:", sksurv.__version__)
import cvxopt; print("cvxopt:", cvxopt.__version__)
import cvxpy; print("cvxpy:", cvxpy.__version__)
import numexpr; print("numexpr:", numexpr.__version__)
import osqp; print("osqp:", osqp.OSQP().version())
```

**Comment by sebp** [comment]
Please do not just post the issue template!

Follow the instructions outlined in the issue template, otherwise it is 
impossible for me to know that your issue is and cannot help you.

**Comment by SurajitTest** [comment]
I tried to upgrade to scikit-survival 0.13 from scikit-survival 0.12 using command 'pip install -U scikit-survival' but unfortunately, installation failed because of scikit-survival 0.13 using PEP 517. I then went the conda path and was successfully able to install
scikit-survival 0.13.

**Comment by sebp** [comment]
Again, please follow the instructions in the issue template and give 
_detailed_ instructions on what the error message is and how to 
reproduce the error.

**Comment by SurajitTest** [comment]
The given below screenshots provide an idea about the error encountered when I tried to upgrade to scikit-survival 0.13 from scikit-survival 0.12 using command 'pip install -U scikit-survival' 

![image](https://user-images.githubusercontent.com/59294362/86301700-dcb97e80-bc49-11ea-878e-b946d2dfd135.png)

![image](https://user-images.githubusercontent.com/59294362/86301725-ed69f480-bc49-11ea-94b7-5c86853e7b09.png)

**Comment by sebp** [comment]
I'm afraid the information you provided is not enough. I would need the 
full output produced when executing `pip install -v -U scikit-survival` 
to have a chance of understanding what might be the problem.

**Comment by SurajitTest** [comment]
Infact when I did fail in upgrading from scikit-survival 0.12 to scikit-survival 0.13 using the command 'pip install -U scikit-survival', I did then use conda for upgrading from scikit-survival 0.12 to scikit-survival 0.13  using the command 'conda install -c sebp scikit-survival'. Sorry, I have not saved the complete output of error  when trying to upgrade using the command 'pip install -U scikit-survival'.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.

**Comment by Husain-Kapadia** [comment]
I faced the same issue as above for installing `scikit-survivial 0.15.0.post0`. I installed it with the command `pip install -vU scikit-survival`. I have installed all dependencies listed on your documentations page. 

I get the following error. This a a part of the stacktrace. I could not copy all sicne the error message is huge and i reached the copy limit. https://pastebin.com/HXy65ZMc
