### ISSUE TITLE
Predicting on right-censored data

### ISSUE THREAD

**Issue by jlim13** [sebp/scikit-survival#128]
When predicting on right-censored data, is there an option to condition on prior duration like in the lifelines package? Or does the predict function do this conditional for us. https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction-on-censored-subjects

**Comment by sebp** [comment]
There's no built-in function to do that, but as the lifelines documentation states, all you need to do is divide by `S(s)`. If you have an individual survival function as `StepFunction`, which `predict_survival_function` can give you, you just need to evaluate it at `s`. Once you have `S(s)`, compute `S(t)` as usual and divide by `S(s)` as before. Hope that helps.

**Comment by jlim13** [comment]
so lets say I am predicting an individual's survival function conditioned on them being alive for `s` days. I would:

1. call `predict_survival_function` which gives me `S()`
2. get the value at `S(s)`
3. divide all of `S()` by `S(s)`?

**Comment by sebp** [comment]
Yes, predict_survival_function will give you `S` (functions) for each sample, from which you can compute `S(t)` and `S(s)`. You can have a look at the introduction notebook to see how the code would look like.
