### ISSUE TITLE
Time periods obtained from using the predict_survival_function() and predict_cumulative_hazard_function() methods of CoxnetSurvivalAnalysis(), CoxPHSurvivalAnalysis() and RandomSurvivalForest() are bound by the upper and lower limits of time periods of the training dataset.

### ISSUE THREAD

**Issue by SurajitTest** [sebp/scikit-survival#129]
The requirement is to obtain time periods using the predict_survival_function() that are not bound by the upper and lower limits of time periods of the training dataset. 

Along with the predict_survival_function(), the same can be extended to predict_cumulative_hazard_function() as well

Attached program :CoxPH_Random_Survival_Forest_GridSearchCV_Sent_Sebastian_July_08_2020.txt helps to replicate scenario for predict_survival_function() only for CoxnetSurvivalAnalysis(), CoxPHSurvivalAnalysis() and RandomSurvivalForest()
[CoxPH_Random_Survival_Forest_GridSearchCV_Sent_Sebastian_July_08_2020.txt](https://github.com/sebp/scikit-survival/files/4888638/CoxPH_Random_Survival_Forest_GridSearchCV_Sent_Sebastian_July_08_2020.txt)

**Comment by sebp** [comment]
I'm sorry, but I'm not going to go through 500 lines of code, please add a **minimal working example** that's illustrates the problem.

**Comment by SurajitTest** [comment]
Attached file : CoxPH_Random_Survival_Forest_GridSearchCV_Sent_Sebastian_July_08_2020_New.txt highlights the issue for predict_survival_function() using train dataset and CoxPHSurvivalAnalysis(). The same issue happens for predict_survival_function() using 
-- train datset when CoxnetSurvivalAnalysis() OR  RandomSurvivalForest() is used
-- test dataset when CoxPHSurvivalAnalysis() OR CoxnetSurvivalAnalysis() OR  RandomSurvivalForest() is used.

[CoxPH_Random_Survival_Forest_GridSearchCV_Sent_Sebastian_July_08_2020_New.txt](https://github.com/sebp/scikit-survival/files/4890175/CoxPH_Random_Survival_Forest_GridSearchCV_Sent_Sebastian_July_08_2020_New.txt)

**Comment by sebp** [comment]
You can't evaluate the survival function or CHF at a time point larger than the what's in the data, because there's no information to estimate the baseline survival function (CHF) from and thus the output is undefined. This works as intended.

**Comment by SurajitTest** [comment]
For time points not in data, was just wondering if any interpolation technique could be used appropriately ?
