### ISSUE TITLE
For sklearn 0.19, cvxpy install differs for me

### ISSUE THREAD

**Issue by pavopax** [sebp/scikit-survival#13]
It seems I need to install `cvxpy` separately than from `requirements.txt`

I follow instructions, and get:....

```bash
(sksurv) scikit-survival$ conda install --file requirements.txt
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:

  - cvxpy

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

so instead, I do:
1. set up blank environment `sksurv`
2. into that env, [install cvxpy](https://cvxgrp.github.io/cvxpy/install/index.html) 
3. comment out `cvxpy` from this repo's requirements.txt
4. now, `conda install --file requirements.txt` and
5. `python setup.py install` [for me, fails the first time - need to install Cython manually]

(FWIW)

macOS Sierra, Bash

**Comment by sebp** [comment]
cvxpy is available from Anaconda's sebp channel. Therefore, you need to run
```
conda install --file requirements.txt
```

I updated the README to reflect this.
