### ISSUE TITLE
Modifying the Split Criterion in Random Survival Forests

### ISSUE THREAD

**Issue by mastervii** [sebp/scikit-survival#131]
Hi, I am using the Random Survival Forests and was wondering whether it is possible to modify the split criterion. Specifically, I would like to make some minor changes to the log-rank test such that it works like Wilcoxon or Tarone and Ware test. If yes, which part of the code should I look for?

**Comment by sebp** [comment]
The split criterion is implemented in Cython here:

https://github.com/sebp/scikit-survival/blob/master/sksurv/tree/_criterion.pyx

**Comment by mastervii** [comment]
Thanks for your answer before.

Now, I am trying to compile _criterion.pyx, the Cython file, but it failed since this module requires some extra C libraries such as NumPy or a special build setup as far as I understand. How should I do to fix this?

If you need more details about the error, please let me know.

**Comment by sebp** [comment]
The documentation contains a section on setting up an development 
environment at 
https://scikit-survival.readthedocs.io/en/latest/contributing.html

Depending on your operating system, you need to install a C/C++ 
compiler, too. See 
https://scikit-survival.readthedocs.io/en/latest/install.html#from-source
