### ISSUE TITLE
do you know similar package but easy to install?

### ISSUE THREAD

**Issue by Sandy4321** [sebp/scikit-survival#137]
do you know similar package but easy to install?

you do need:

Requirements
Python 3.5 or later
cvxpy
cvxopt
joblib
numexpr
numpy 1.12 or later
osqp
pandas 0.21 or later
scikit-learn 0.22 or 0.23
scipy 1.0 or later
C/C++ compiler

**Comment by CamDavidsonPilon** [comment]
Speaking as a Python scientific developer and user, I don't think these requirements are very difficult to satisfy - especially for a modern computational environment that enables scikit-learn / scikit-survival.  Is there a specific requirement on that list that you are having trouble with?

**Comment by sebp** [comment]
If you want to compile everything from scratch, it can get tricky, but you can install pre-compiled packages of scikit-survival and its dependencies via [Anaconda](https://scikit-survival.readthedocs.io/en/latest/install.html). If that doesn't solve your problem, it would be very helpful if you could give more details on what issues you are facing during installation.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
