### ISSUE TITLE
questions about cumulative_dynamic_auc function

### ISSUE THREAD

**Issue by hgjlee** [sebp/scikit-survival#145]
Thanks for making this awesome library available. I was wondering what is used as the cutoff threshold for determining the event outcome given a risk score in the cumulative_dynamic_auc function. There's another library for getting time-dependent AUCs in R called [timeROC](https://github.com/cran/timeROC/blob/master/R/timeROC_3.R) ([manual](https://cran.r-project.org/web/packages/timeROC/timeROC.pdf)). which yielded conflicting results for my experiments. It also references the same papers and doesn't seem to have any differences in terms of algorithm. Would you be able to share some pointers?

**Comment by sebp** [comment]
I'm not sure if I fully understand what you mean by "cutoff threshold". If you mean over which intervals the integral is computed, this is the `times` argument and needs to be provided by the user. If you post your Python code along side the R/timeROC code, I probably can tell you what is going on.

**Comment by hgjlee** [comment]
Thank you for your reply! c in the following equations from [this paper](https://diagnprognres.biomedcentral.com/articles/10.1186/s41512-019-0057-6) is what I meant by the "cutoff threshold." M represents the risk score and D represents event.
![Screen Shot 2020-10-08 at 8 56 12 AM](https://user-images.githubusercontent.com/11896786/95461390-2b12a380-0944-11eb-9c14-73a56d149f0d.png)

I'm currently getting errors with my private dataset at the moment, but I'll reproduce them with a small publicly available dataset and share them with you shortly. It'd be fantastic if you could take a look.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
