### ISSUE TITLE
Scikit-Survival LinAlg Error 

### ISSUE THREAD

**Issue by sahar90o** [sebp/scikit-survival#168]
Hello, 
I am trying to fit each column of my dataset to the CoxPH SurvivalAnalysis function in order to compute CI for each feature. I tried to use a for loop to fit each feature iteratively, However, I got the singular matrix error. On the other hand, when I fit the same feature to the Cox function out of a loop, it works well and gives me the CI. Can anybody help me with this problem?

Here is my code :
CINDEX = []
Coxph = CoxPHSurvivalAnalysis()
for a in range(len(Xscaled.columns)): 
    feature = np.reshape(np.array(Xscaled.iloc[:,a]),(-1,1))
    Coxph.fit(feature,Y)
    score = Coxph.score(feature,Y)
    CINDEX.append(score)

This is the error : 

 LinAlgError                               Traceback (most recent call last)
<ipython-input-56-155b2b43d4f5> in <module>
      3 for a in range(len(Xscaled.columns)):
      4     feature = np.reshape(np.array(Xscaled.iloc[:,a]),(-1,1))
----> 5     Coxph.fit(feature,Y)
      6     score = Coxph.score(feature,Y)
      7     CINDEX.append(score)

~\Anaconda3\lib\site-packages\sksurv\linear_model\coxph.py in fit(self, X, y)
    403             optimizer.update(w)
    404             delta = solve(optimizer.hessian, optimizer.gradient,
--> 405                           overwrite_a=False, overwrite_b=False, check_finite=False)
    406 
    407             if not numpy.all(numpy.isfinite(delta)):

~\Anaconda3\lib\site-packages\scipy\linalg\basic.py in solve(a, b, sym_pos, lower, overwrite_a, overwrite_b, debug, check_finite, assume_a, transposed)
    214                                                (a1, b1))
    215         lu, ipvt, info = getrf(a1, overwrite_a=overwrite_a)
--> 216         _solve_check(n, info)
    217         x, info = getrs(lu, ipvt, b1,
    218                         trans=trans, overwrite_b=overwrite_b)

~\Anaconda3\lib\site-packages\scipy\linalg\basic.py in _solve_check(n, info, lamch, rcond)
     29                          '.'.format(-info))
     30     elif 0 < info:
---> 31         raise LinAlgError('Matrix is singular.')
     32 
     33     if lamch is None:

LinAlgError: Matrix is singular

**Comment by sebp** [comment]
Does this issue arise for every column in your dataset, or only for a few columns?

The only reason I could think why this could happen for a single feature is if it is nearly constant. What is the standard deviation of the feature that causes this error?

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
