### ISSUE TITLE
issue when try to install scikit-survival in windows 10

### ISSUE THREAD

**Issue by csetraynor** [sebp/scikit-survival#17]
Hi, I have no issue when I install it in my Linux, but at the universityI am working in a Windows Machine and it is no way I can go around this main issue that is that it is that the command to install from conda does not work for me.  It is that I need to change the channel? I try install pip  and unfortunately it did not work, could you share the binary? I think it would be the only way to go around this. 
![scikit-surv](https://user-images.githubusercontent.com/33321804/33391035-aa762404-d52f-11e7-97c2-021a07fedbb1.PNG)

Any way, I want to congratulate the team that is working on this ! good job!

**Comment by sebp** [comment]
I haven't built conda packages for Windows, yet. Installing via pip should work, could you please post the error message?

In the meantime you can obtain a pre-built wheel file from https://ci.appveyor.com/project/sebp/scikit-survival/build/1.0.119/job/f3c6fsrtm062rnvl/artifacts

**Comment by csetraynor** [comment]
Hi @sebp ,
Yes of course the issue was the following 
![scikit-surv](https://user-images.githubusercontent.com/33321804/33425725-7b75f69c-d5b7-11e7-99a0-4951f805b02a.PNG)

I had no problem though installing via wheel file. thank you very much !
