### ISSUE TITLE
"pip install -e ." breaks. 

### ISSUE THREAD

**Issue by jlim13** [sebp/scikit-survival#184]
I am trying to install in develop mode to work on some functionality, but I get this error: 

<img width="1440" alt="Screen Shot 2021-03-06 at 10 18 37 PM" src="https://user-images.githubusercontent.com/36393441/110227793-e75ba000-7ec9-11eb-9434-7436777c9c37.png">

**Comment by sebp** [comment]
Could you please run `python setup.py build_ext --inplace -f` and paste 
the output here?

**Comment by jlim13** [comment]
<img width="1440" alt="Screen Shot 2021-03-07 at 1 41 28 PM" src="https://user-images.githubusercontent.com/36393441/110250724-d30bb780-7f4a-11eb-99cc-883c5c65b178.png">

**Comment by jlim13** [comment]
I also already have eigen installed via homebrew

**Comment by sebp** [comment]
Looks like you haven't initialized submodules, see
https://scikit-survival.readthedocs.io/en/latest/contributing.html#creating-a-fork

**Comment by jlim13** [comment]
ah gotcha, thanks for the clarification!
