### ISSUE TITLE
Potential issue in user guide for CoxnetSurvivalAnalysis

### ISSUE THREAD

**Issue by mfergie** [sebp/scikit-survival#186]
From my understanding of the user guide on `CoxnetSurvivalAnalysis`, the GridSearchCV should be evaluated over the set of alphas identified by fitting the CoxNet model to the full data. Instead, it is ran over the set of alphas defined using `linspace` further up in the code. 

Unless I'm mistaken, the code in box 11 should be:
```python
cv = KFold(n_splits=5, shuffle=True, random_state=0)
gcv = GridSearchCV(
    make_pipeline(StandardScaler(), CoxnetSurvivalAnalysis(l1_ratio=0.9)),
    param_grid={
        "coxnetsurvivalanalysis__alphas": [
            [v] for v in coxnet_pipe.named_steps["coxnetsurvivalanalysis"].alphas_
        ]
    },
    cv=cv,
    error_score=0.5,
    n_jobs=4).fit(Xt, y)

cv_results = pd.DataFrame(gcv.cv_results_)
```

This gives different results:
<img width="659" alt="Screenshot 2021-03-13 at 18 21 06" src="https://user-images.githubusercontent.com/1122852/111039994-f17d2180-8428-11eb-81db-99d9a3e81db3.png">

P.s. thanks for all your work on this library.

**Comment by sebp** [comment]
Good catch! It explains why the graph looked so weird.
