### ISSUE TITLE
Pandas 0.18?

### ISSUE THREAD

**Issue by dhhagan** [sebp/scikit-survival#2]
Is there a reason pandas 0.18 is required and not >=0.18?

**Comment by sebp** [comment]
Support for pandas 0.19 has been added in commit b21bc131c673c23e8e9171b0900ef4b8e203ca10. I haven't checked pandas 0.20, yet.

**Comment by sebp** [comment]
Support for pandas 0.20 has been added in commit 64ed7d0714e5a917f86b0ea099d9f18daa8ecee5 and is available in v0.2.
