### ISSUE TITLE
CoxnetSurvivalAnalysis code example

### ISSUE THREAD

**Issue by hyunjaecho94** [sebp/scikit-survival#202]
**Describe the bug**

I was following the code snippets in https://scikit-survival.readthedocs.io/en/latest/api/generated/sksurv.linear_model.CoxnetSurvivalAnalysis.html but I get 

> ValueError                                Traceback (most recent call last)
> <ipython-input-40-0f447a2f3864> in <module>
>       1 for alpha, surv_alpha in surv_funcs.items():
>       2     for fn in surv_alpha:
> ----> 3         plt.step(fn.x, fn(fn.x), where="post",
>       4                  label="alpha = {:.3f}".format(alpha))
>       5 
> 
> ~/Library/Python/3.7/lib/python/site-packages/sksurv/functions.py in __call__(self, x)
>      45 
>      46     def __call__(self, x):
> ---> 47         if not numpy.isfinite(x):
>      48             raise ValueError("x must be finite")
>      49         if x < self.x[0] or x > self.x[-1]:
> 
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Code Sample to Reproduce the Bug**

`fn(fn.x)` seems to be causing it.

**Versions**

System:
    python: 3.7.6 (default, Dec 30 2019, 19:38:26)  [Clang 11.0.0 (clang-1100.0.33.16)]
executable: /usr/local/opt/python/bin/python3.7
   machine: Darwin-20.4.0-x86_64-i386-64bit

Python dependencies:
       pip: 21.1.1
setuptools: 54.2.0
   sklearn: 0.22.2.post1
     numpy: 1.19.5
     scipy: 1.6.2
    Cython: 0.29.17
    pandas: 1.2.3
matplotlib: 3.4.1
    joblib: 1.0.1

Built with OpenMP: True
sksurv: 0.12.0
cvxopt: 1.2.6
cvxpy: 1.1.13
numexpr: 2.7.3
osqp: 0.6.2`

**Comment by sebp** [comment]
The user guide is referring to the most recent version of scikit-survival.

`StepFunction` instances can be evaluated at multiple points with a single call since version 0.13.0, but you are using 0.12.0.
