### ISSUE TITLE
Method _validate_data not part of CoxnetSurvivlAnalysis

### ISSUE THREAD

**Issue by jendawkins** [sebp/scikit-survival#207]
I'm not sure if I have something installed incorrectly, but when I try to run Coxnet survival analysis, I can't fit to my pre-standardized data as I get the attribute error 'CoxnetSurvivalAnalysis' object has no attribute '_validate_data'.

In coxnet.py's fit function, the first line (238) is `X, event_num, time, X_offset, X_scale = self._pre_fit(X, y)`
In self._pre_fit, line 143: `X = self._validate_data(X)`
But there is no self._validate_data within the module.

**Code Sample to Reproduce the Bug**

```python
model2 = CoxnetSurvivalAnalysis(l1_ratio = 1, penalty_factor = 1)
model2.fit(x,y)
```
Instead of fitting to the data, I get the attribute error AttributeError: 'CoxnetSurvivalAnalysis' object has no attribute '_validate_data'

**Versions**
System:
    python: 3.7.0 (default, Jun 28 2018, 07:39:16)  [Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /Users/jendawk/miniconda3/bin/python
   machine: Darwin-19.6.0-x86_64-i386-64bit

Python dependencies:
       pip: 21.1.1
setuptools: 54.2.0
   sklearn: 0.22.1
     numpy: 1.19.2
     scipy: 1.5.0
    Cython: 0.29.23
    pandas: 1.0.5
matplotlib: 3.2.2
    joblib: 1.0.1

Built with OpenMP: True
sksurv: 0.15.0.post0
cvxopt: 1.2.0
numexpr: 2.7.3
osqp: 0.5.0

**Comment by sebp** [comment]
You need scikit-learn 0.24 with scikit-survival 0.15, but you have 0.22.

I'm surprised it actually worked to compile scikit-survival
