### ISSUE TITLE
Cannot install scikit-survival on Google colab

### ISSUE THREAD

**Issue by Aman211409** [sebp/scikit-survival#211]
I am not able to install scikit-survival on Google colab through pip install.
```python

!pip install scikit-survival
# This example should be as succinct as possible and self-contained,
# i.e., not rely on external data.
# We are going to copy-paste your code and we expect to get the same result as you.
# It should run in a fresh python session, and so include all relevant imports.
```

**Expected Results**

**Actual Results**
Collecting scikit-survival
  Using cached https://files.pythonhosted.org/packages/91/f0/047ce90bb831ab34ca287d1d23f0c61b6546cd89494566898c0e17516990/scikit-survival-0.15.0.post0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpcjalubg4 Check the logs for full command output.
**Versions**
Please execute the following snippet and paste the output below.

```python
import sklearn; sklearn.show_versions()
import sksurv; print("sksurv:", sksurv.__version__)
import cvxopt; print("cvxopt:", cvxopt.__version__)
import cvxpy; print("cvxpy:", cvxpy.__version__)
import numexpr; print("numexpr:", numexpr.__version__)
import osqp; print("osqp:", osqp.OSQP().version())
```
System:
    python: 3.7.10 (default, May  3 2021, 02:48:31)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
       pip: 19.3.1
setuptools: 57.0.0
   sklearn: 0.22.2.post1
     numpy: 1.19.5
     scipy: 1.4.1
    Cython: 0.29.23
    pandas: 1.1.5
matplotlib: 3.2.2
    joblib: 1.0.1

Built with OpenMP: True

**Comment by sebp** [comment]
I'm sorry, but if you don't provide any information on what the error 
is, I cannot help you.

In addition, you can try Binder: 
https://mybinder.org/v2/gh/sebp/scikit-survival/master

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
