### ISSUE TITLE
Accelerate ```compare_survival``` function

### ISSUE THREAD

**Issue by raynardj** [sebp/scikit-survival#214]
# To accelerate ```compare_survival``` function 🚀
**Is your feature request related to a problem? Please describe.**

The [sksurv.compare.compare_survival](https://github.com/sebp/scikit-survival/blob/master/sksurv/compare.py) function can take seconds to minutes to run when we have large n_groups. It could be 10x to 30x faster

https://github.com/sebp/scikit-survival/blob/c4fb76489fe7779705fbca663aa52c5159ec1a2e/sksurv/compare.py#L95-L99

**Describe the solution you'd like**
We can try to use more numpy-ish operation to speed up the large cartesian product of ```covar```(n_groups x n_groups).

**Describe alternatives you've considered**

Here's the possible alternative, tested on ```n_groups=200``` dummy data, comparing the original & changed performance

```python
from sksurv.datasets import load_whas500
from sksurv.compare import compare_survival
from sksurv.compare import check_arrays_survival, stats
import numpy
import pandas
```

```python
data = load_whas500()
```

```python
x, y = data
```

In cases where the n_groups is wide

```python
x_dummy = np.random.randint(0,200, size=(500))
```

```python
%%time
chisq, pval, table, covar = compare_survival(y, x_dummy, return_stats=True)
chisq, pval, table, covar.shape
```

    CPU times: user 3.66 s, sys: 906 ms, total: 4.56 s
    Wall time: 3.27 s

    (364.6872320013692,
     3.650066287189857e-14,
            counts  observed  expected  statistic
     group                                       
     0           4         2  1.925727   0.074273
     1           2         1  0.380651   0.619349
     2           2         1  0.928238   0.071762
     3           2         0  1.311987  -1.311987
     5           1         1  0.069986   0.930014
     ...       ...       ...       ...        ...
     195         2         0  1.311987  -1.311987
     196         2         1  0.724047   0.275953
     197         2         1  0.978378   0.021622
     198         2         2  0.880811   1.119189
     199         7         2  3.445353  -1.445353
     
     [184 rows x 4 columns],
     (184, 184))

```python
def compare_survival2(y, group_indicator, return_stats=False):
    """K-sample log-rank hypothesis test of identical survival functions.

    Compares the pooled hazard rate with each group-specific
    hazard rate. The alternative hypothesis is that the hazard
    rate of at least one group differs from the others at some time.

    See [1]_ for more details.

    Parameters
    ----------
    y : structured array, shape = (n_samples,)
        A structured array containing the binary event indicator
        as first field, and time of event or time of censoring as
        second field.

    group_indicator : array-like, shape = (n_samples,)
        Group membership of each sample.

    return_stats : bool, optional, default: False
        Whether to return a data frame with statistics for each group
        and the covariance matrix of the test statistic.

    Returns
    -------
    chisq : float
        Test statistic.
    pvalue : float
        Two-sided p-value with respect to the null hypothesis
        that the hazard rates across all groups are equal.
    stats : pandas.DataFrame
        Summary statistics for each group:  number of samples,
        observed number of events, expected number of events,
        and test statistic.
        Only provided if `return_stats` is True.
    covariance : array, shape=(n_groups, n_groups)
        Covariance matrix of the test statistic.
        Only provided if `return_stats` is True.

    References
    ----------
    .. [1] Fleming, T. R. and Harrington, D. P.
           A Class of Hypothesis Tests for One and Two Samples of Censored Survival Data.
           Communications In Statistics 10 (1981): 763-794.
    """

    group_indicator, event, time = check_arrays_survival(
        group_indicator, y, dtype="O", ensure_2d=False)

    n_samples = time.shape[0]
    groups, group_counts = numpy.unique(group_indicator, return_counts=True)
    n_groups = groups.shape[0]
    if n_groups == 1:
        raise ValueError("At least two groups must be specified, "
                         "but only one was provided.")

    # sort descending
    o = numpy.argsort(-time, kind="mergesort")
    x = group_indicator[o]
    event = event[o]
    time = time[o]

    at_risk = numpy.zeros(n_groups, dtype=numpy.int_)
    observed = numpy.zeros(n_groups, dtype=numpy.int_)
    expected = numpy.zeros(n_groups, dtype=numpy.float_)
    covar = numpy.zeros((n_groups, n_groups), dtype=numpy.float_)
    k = 0
    # CHANGE NO 2 here
    gi = numpy.eye(n_groups, dtype=bool)
    
    while k < n_samples:
        ti = time[k]
        total_events = 0
        while k < n_samples and ti == time[k]:
            idx = numpy.searchsorted(groups, x[k])
            if event[k]:
                observed[idx] += 1
                total_events += 1
            at_risk[idx] += 1
            k += 1

        if total_events != 0:
            total_at_risk = k
            expected += at_risk * (total_events / total_at_risk)
            if total_at_risk > 1:
                multiplier = total_events * (total_at_risk - total_events) / (total_at_risk * (total_at_risk - 1))
                
                # CHANGE NO 2 here
                temp = at_risk * multiplier
                covar[gi] += temp
                covar -= (temp[:,None]* at_risk[None,:] / total_at_risk)

    df = n_groups - 1
    zz = observed[:df] - expected[:df]
    chisq = numpy.linalg.solve(covar[:df, :df], zz).dot(zz)
    pval = stats.chi2.sf(chisq, df)

    if return_stats:
        table = OrderedDict()
        table["counts"] = group_counts
        table["observed"] = observed
        table["expected"] = expected
        table["statistic"] = observed - expected
        table = pandas.DataFrame.from_dict(table)
        table.index = pandas.Index(groups, name="group")
        return chisq, pval, table, covar

    return chisq, pval
```

Performance can improve at least 10x

```python
%%time
chisq2, pval2, table2, covar2 = compare_survival2(y, x_dummy, return_stats=True)
chisq2, pval2, table2, covar2.shape
```

    CPU times: user 321 ms, sys: 262 ms, total: 583 ms
    Wall time: 49.9 ms

    (364.6872320013692,
     3.650066287189857e-14,
            counts  observed  expected  statistic
     group                                       
     0           4         2  1.925727   0.074273
     1           2         1  0.380651   0.619349
     2           2         1  0.928238   0.071762
     3           2         0  1.311987  -1.311987
     5           1         1  0.069986   0.930014
     ...       ...       ...       ...        ...
     195         2         0  1.311987  -1.311987
     196         2         1  0.724047   0.275953
     197         2         1  0.978378   0.021622
     198         2         2  0.880811   1.119189
     199         7         2  3.445353  -1.445353
     
     [184 rows x 4 columns],
     (184, 184))

Check if the result is the same

```python
chisq==chisq2, pval==pval2, (table==table2).mean(), (covar==covar2).astype(np.float32).min()
```

    (True,
     True,
     counts       1.0
     observed     1.0
     expected     1.0
     statistic    1.0
     dtype: float64,
     1.0)

The changed lines of code:
```python
gi = np.eye(n_groups)

temp = at_risk * multiplier
covar[gi] += temp
covar -= (temp[:,None]* at_risk[None,:] / total_at_risk)
```

**Comment by raynardj** [comment]
I'll make PR if ok

**Comment by sebp** [comment]
Thanks for helping to improve scikit-survival!

Could you please create a PR and I'll review the suggested changes.
