### ISSUE TITLE
Unable to pip install scikit survival on MacOs

### ISSUE THREAD

**Issue by Husain-Kapadia** [sebp/scikit-survival#216]
**Describe the bug**

I faced a similar issues as in #126 for installing scikit-survivial 0.15.0.post0. 
I installed it with the command `pip install -vU scikit-survival`. I have installed all dependencies listed on your documentations page.

I get the following error. This a a part of the stack trace. I could not copy all since the error message is huge and i reached the copy limit. https://pastebin.com/HXy65ZMc

**Versions**
Please execute the following snippet and paste the output below.

```python
import sklearn; sklearn.show_versions()
import sksurv; print("sksurv:", sksurv.__version__)
import cvxopt; print("cvxopt:", cvxopt.__version__)
import cvxpy; print("cvxpy:", cvxpy.__version__)
import numexpr; print("numexpr:", numexpr.__version__)
import osqp; print("osqp:", osqp.OSQP().version())

System:
    python: 3.7.4 (default, Apr 12 2021, 07:19:34)  [Clang 12.0.0 (clang-1200.0.32.29)]
executable: /Users/husain.kapadia/.pyenv/versions/err_venv/bin/python
   machine: Darwin-20.5.0-x86_64-i386-64bit
Python dependencies:
          pip: 21.1.3
   setuptools: 57.2.0
      sklearn: 0.24.2
        numpy: 1.21.0
        scipy: 1.7.0
       Cython: None
       pandas: 1.2.4
   matplotlib: None
       joblib: 1.0.1
threadpoolctl: 2.2.0
Built with OpenMP: True
cvxopt: 1.2.6
numexpr: 2.7.3
osqp: 0.6.2
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'sksurv'

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'cvxpy'
```

**Comment by sebp** [comment]
I would guess that something is wrong with the command line tools. Maybe executing
`sudo xcode-select -r` will help. Otherwise, a similar error and several solutions have been discussed in https://github.com/PointCloudLibrary/pcl/issues/2601

**Comment by Husain-Kapadia** [comment]
my default sdk path was initially pointing to `/Library/Developer/CommandLineTools`. So, I downloaded Xcode.app from Apple Software store and set the xcode-select path to `/Applications/Xcode.app/Contents/Developer`. However, it still has the same error. Here are the logs. https://pastebin.com/3yTvVZEe

**Comment by sebp** [comment]
I'm wondering whether it has something to do with macOS Big Sur? Unfortunately, I only have access to Catalina, so I can't check myself.

**Comment by Husain-Kapadia** [comment]
Perhaps, that could be. I will keep trying and see if I can fix the problem and update the thread if I manage to do so.

**Comment by Husain-Kapadia** [comment]
I managed to fix the installation of scikit survival on Big Sur 11.4. I had to edit the `cmath` file in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1` by importing the full path to `math.h` . So, instead of the simple c++ import `#include<math.h>` I changed it to `#include<{full_path_above}/math.h>` and everything worked. :aaw_yeah:. So we can close this issue. Thanks for your inputs @sebp
