### ISSUE TITLE
RandomSurvivalForest performance depends on column order of features

### ISSUE THREAD

**Issue by codingS3b** [sebp/scikit-survival#219]
**Describe the bug**
I'm not sure if this is intended behaviour or not (or can at least be explained), but it seems strange to me. The random survival forest produces different performance results if I simply change the order of the features in the data.

**Code Sample to Reproduce the Bug**

```python
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sksurv.ensemble import RandomSurvivalForest
from sksurv.datasets import load_veterans_lung_cancer

import numpy as np

df, y = load_veterans_lung_cancer()

# flip two features around
feat_cols_a = [
     "Age_in_years",
     "Karnofsky_score",
     "Months_from_Diagnosis",
]
X_a = df[feat_cols_a].to_numpy()

feat_cols_b = [
     "Age_in_years",
     "Months_from_Diagnosis",
     "Karnofsky_score",
]
X_b = df[feat_cols_b].to_numpy()

assert np.all(np.isclose(X_a[:, :-2], X_b[:, :-2]))
assert np.all(X_a[:, -1] == X_b[:, -2])
assert np.all(X_a[:, -2] == X_b[:, -1])

# NOTE: I fixed the seed of the model to control randomness
model = RandomSurvivalForest(n_estimators=10, random_state=42)
print(model)


scores_a = cross_val_score(model, X_a, y, cv=KFold(n_splits=3, shuffle=True, random_state=42))
print("score on each fold for a)", scores_a)

scores_b = cross_val_score(model, X_b, y, cv=KFold(n_splits=3, shuffle=True, random_state=42))
print("score on each fold for b)", scores_b)
```

**Expected Results**
Since the features passed to the random forest are the same, I would expect to get the same performance out of the model (aside from randomness which I hopefully controlled for by setting the `random_state` parameter.

**Actual Results**
The output of the above script is the following
```bash
score on each fold for a) [0.69573835 0.61093911 0.70801317]
score on each fold for b) [0.67690783 0.59545924 0.69648738]
```
which shows that performance changes if we simply change the ordering of the features.

**Versions**

```bash
   python: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00)  [GCC 7.5.0]
   machine: Linux-5.4.0-58-generic-x86_64-with-glibc2.10

Python dependencies:
          pip: 21.1.1
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.2
        numpy: 1.20.2
        scipy: 1.6.2
       Cython: None
       pandas: 1.2.4
   matplotlib: 3.4.2
       joblib: 1.0.1
threadpoolctl: 2.1.0

Built with OpenMP: True
sksurv: 0.15.0.post0
cvxopt: 1.2.6
cvxpy: 1.1.15
numexpr: 2.7.3
osqp: 0.6.2

**Comment by sebp** [comment]
I would argue that this is expected, because fixing `random_state` determines which column indices are (randomly) selected at each split. If you change what the i-th column represents (by reordering), you will get a different split for that feature.

**Comment by codingS3b** [comment]
Thanks for answering! 
Okay, that makes kind of sense. It is still a little strange to me since e.g. in a (conceptually much simpler) Cox model, the order of the features will not affect the value of the estimated parameters and hence model performance will stay the same. But I guess this can not be expected from algorithms that involve some randomness...
This makes life quite a bit harder when trying to tune pipeline hyperparameters if the order of the features has an effect as well :/

**Comment by sebp** [comment]
It should only have big influence if the ensemble is very small (like in your example) or the depth of trees is very small. If you evaluate enough splits, the randomness should just average out over the entire ensemble.

**Comment by raminsalmas** [comment]
I'm wondering which scoring metrics you used here? I'm sure it's not concordance_index.

**Comment by sebp** [comment]
> I'm wondering which scoring metrics you used here? I'm sure it's not concordance_index.

sklearn will use the `score` method, which returns the concordance index by default.

**Comment by raminsalmas** [comment]
How does it work in "GridSearchCV"?

**Comment by aridf** [comment]
Quick follow-up on this, and not strictly on-topic... how can one change the scoring behavior here to use integrated brier score?

**Comment by sebp** [comment]
See 
https://scikit-survival.readthedocs.io/en/latest/user_guide/evaluating-survival-models.html#Using-Metrics-in-Hyper-parameter-Search
