### ISSUE TITLE
Inconsistent ouptut using penality Cox models

### ISSUE THREAD

**Issue by jackyko1991** [sebp/scikit-survival#223]
I am checking the consistency between Lifelines and Scikit-survival for penality Cox models.

[https://gist.github.com/jackyko1991/bd0e605fa03b2c3e244d08db2b68edd8](https://gist.github.com/jackyko1991/bd0e605fa03b2c3e244d08db2b68edd8)

When using standard Cox model (alpha = 0 and l1 = 0), the results with different estimators are the same.

However when using penality models including ridge and lasso regression, even `CoxPHSurvivalAnalysis` and `CoxnetSurvivalAnalysis` produce different hazard ratios but the same concordance index.

Also is there any method to calculate confidence interval of coefficients like Lifeline? This is necessary when publishing clinical journals, which makes me struggle to use scikit-survial for scientific researches.

**Comment by sebp** [comment]
> However when using penality models including ridge and lasso regression, even CoxPHSurvivalAnalysis and CoxnetSurvivalAnalysis produce different hazard ratios but the same concordance index.

I'm not familiar with the internals of lifelines, but I would assume that it uses a different optimization scheme than scikit-survival, which leads to the differences.

> Also is there any method to calculate confidence interval of coefficients like Lifeline? This is necessary when publishing clinical journals, which makes me struggle to use scikit-survial for scientific researches.

See #61.
