### ISSUE TITLE
Test failure on aarch64-linux

### ISSUE THREAD

**Issue by rmcgibbo** [sebp/scikit-survival#224]
**Describe the bug**

I noticed that this package fails its tests on aarch64-linux. Here's an example of the test log with python38: https://hydra.nixos.org/log/4z3fvm21b3i7gcpvp8kgz1svq8788wka-python3.8-scikit-survival-0.15.0.post0.drv
Here's another example with python39: https://hydra.nixos.org/log/1j3p76xm4ax8gmzbm6d0zvaqflpvx8w1-python3.9-scikit-survival-0.15.0.post0.drv

It looks to me like the precision in one of the numerics tests is just a tiny bit too tight.

**Comment by sebp** [comment]
Currently, ARM isn't officially supported and not tested during CI. It seems only one test is failing, could you just [disable this particular test](https://docs.pytest.org/en/6.2.x/usage.html#specifying-tests-selecting-tests)?
