### ISSUE TITLE
Add predict_cumulative_hazard_function() and predict_survival_function() to all algorithms

### ISSUE THREAD

**Issue by tienholin** [sebp/scikit-survival#24]
CoxPHSurvivalAnalysis has these 2 methods, predict_cumulative_hazard_function() and predict_survival_function(). Please add them to CoxnetSurvivalAnalysis, GradientBoostingSurvivalAnalysis, FastSurvivalSVM, etc.

I looked up the source code in coxph.py, but would appreciate pointers on how to implement the same thing for other classes, thanks for a great package!

**Comment by sebp** [comment]
Marking as duplicate of #22.
