### ISSUE TITLE
NaiveSurvivalSVM() throws value error when fitting

### ISSUE THREAD

**Issue by carvetighter** [sebp/scikit-survival#25]
I'm going through the tutorial using the veterans lung cancer study and when fitting NaiveSurvivalSVM() the below error is thrown.  The other SVM models work with the same syntax.  the X and y values are the same as in the tutorial.

```
File "u:\Projects.Experiment\scikit-survival\Main.py", line 482, in main 
  model.fit(df_x_numeric, array_y)
File "C:\Program Files\Anaconda3\envs\test\lib\site-packages\sksurv\svm\naive_survival_svm.py", line 
  153, in fit
    x_pairs, y_pairs = self._get_survival_pairs(X, y, random_state)
File "C:\Program Files\Anaconda3\envs\test\lib\site-packages\sksurv\svm\naive_survival_svm.py", line 
  126, in _get_survival_pairs
    x_pairs.resize((k, X.shape[1]))
ValueError: cannot resize an array that references or is referenced by another array in this way.  
  Use the resize function
```

**Comment by sebp** [comment]
Which version of python, numpy, scipy, pandas and scikit-learn are you using?

**Comment by carvetighter** [comment]
Using: 
Python 3.6.0
pandas 0.20.3
scipy 0.19.1
numpy 1.12.1
sklearn 0.19.0

**Comment by sebp** [comment]
I can't seem to reproduce the problem, could you please post a minimal example to demonstrates this issue?

**Comment by carvetighter** [comment]
Well, this is interesting.  I'm using VSCODE, check this out...

Results in DEBUG mode:
    
    starting SvmNv
    exception: cannot resize an array that references or is referenced
    by another array in this way.  Use the resize function
    finishing SvmNv testing

    starting FastSurvivalSVM
    no exception in fitting
    finishing FastSurvivalSVM testing

Results not in DEBUG mode:

    starting SvmNv
    no exception in fitting
    finishing SvmNv testing

    starting FastSurvivalSVM
    no exception in fitting
    finishing FastSurvivalSVM testing

Code:

    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
    #
    # File / Package Import
    #
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#        

    from sksurv.datasets import load_veterans_lung_cancer
    from sksurv.preprocessing import OneHotEncoder
    from sksurv.svm import NaiveSurvivalSVM
    from sksurv.svm import FastSurvivalSVM
    import pandas
    import numpy

    # supress warnings
    import warnings
    warnings.simplefilter('ignore')

    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
    #
    # Main Method
    #
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#

    def main():
        '''
        this is the main method that tests NaiveSurvivalSVM
     
        Requirements:
        package sksurv
        package pandas
    
        Inputs:
        n/a
        Type: n/a
        Desc: n/a
        
      
        Important Info:
        None
    
        Return:
        n/a
        Type: n/a
        Description: n/a
        '''

        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
        #
        # Start
        #
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
        #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#                

        #--------------------------------------------------------------------------#
        # get the data
        #--------------------------------------------------------------------------#

        df_x, array_y = load_veterans_lung_cancer()
        df_x_numeric = OneHotEncoder().fit_transform(df_x)

        #--------------------------------------------------------------------------#
        # startint SvmNv
        #--------------------------------------------------------------------------#

        print('starting SvmNv')
        model = NaiveSurvivalSVM()
        try:
            model.fit(df_x_numeric, array_y)
        except Exception as e:
            print('exception: %s' %e.args)
        else:
            print('no exception in fitting')
        finally:
            print('finishing SvmNv testing')

        #--------------------------------------------------------------------------#
        # startint SvmNv
        #--------------------------------------------------------------------------#

        print('\nstarting FastSurvivalSVM')
        model = FastSurvivalSVM()
        try:
            model.fit(df_x_numeric, array_y)
        except Exception as e:
            print('exception: %s' %e.args)
        else:
            print('no exception in fitting')
        finally:
            print('finishing FastSurvivalSVM testing')

        pass

        # call Main
        if __name__ == '__main__':
            main()

**Comment by sebp** [comment]
I tried on a Windows machine with the versions you mentioned, but couldn't reproduce the problem (I'm using Anaconda).

I don't see how the array could be referenced multiple times if it is used only locally. You could try to create a view instead of resizing the array by replacing
```
x_pairs.resize((k, X.shape[1]))
y_pairs.resize(k)
```
with
```
x_pairs = x_pairs[:k]
y_pairs = y_pairs[:k]
```

**Comment by carvetighter** [comment]
@sebp don't worry about this.  You can close this out.  The issue is with VSCODE not the algorithm.  Thank you for your effort I really appreciate it.
