### ISSUE TITLE
Can not import SurvivalTree

### ISSUE THREAD

**Issue by JEwerszumrode** [sebp/scikit-survival#250]
For scikit-learn version = `1.0.2` and scikit-survival version = `0.17`, I get the following error by simply trying to import the method: 
`from sksurv.tree import SurvivalTree`
which results in:
`ValueError: sklearn.tree._tree.TreeBuilder size changed, may indicate binary incompatibility. Expected 80 from C header, got 72 from PyObject`

**Comment by sebp** [comment]
Which version of Python and numpy are you using?

**Comment by JEwerszumrode** [comment]
Numpy 1.20.1 and Python 3.8; generally running code on a databricks cluster with this setup https://docs.databricks.com/release-notes/runtime/10.3ml.html#python-libraries-on-cpu-clusters 
I installed via Sksurv via `%pip install scikit-survival`

**Comment by JEwerszumrode** [comment]
Going back to scikit-survival version `0.16` without upgrading scikit-learn from `0.24 -> 1.0.2` worked for me

**Comment by sebp** [comment]
sksurv is compiling against sklearn 1.0, but sklearn 1.0.2 has changed the Cython code for Tree (see https://github.com/scikit-learn/scikit-learn/pull/21552/files). This seems to cause the incompatibility.

As workaround, either downgrade sklearn, or manually change sksurv's requirement to 1.0.2.:
https://github.com/sebp/scikit-survival/blob/1af2ebedb88118fa858b8ef27c7578c9e1e99530/pyproject.toml#L11

**Comment by sebp** [comment]
After having a closer look, it seems that sklearn 1.0.0 and  sklearn 1.0.2 *are* binary compatible.

I was only able to reproduce this issue when forcing to compile against 0.24.1, which is not intended to work.

```bash
python -m venv senv
. senv/bin/activate
pip install setuptools_scm wheel Cython osqp pandas ecos numexpr 'scikit-learn==0.24.1'
pip install --no-build-isolation --no-deps -v scikit-survival
pip install -U scikit-learn
python -c "from sksurv.tree import SurvivalTree"
```
