### ISSUE TITLE
get_x_y returning y with Event indicators as only False.

### ISSUE THREAD

**Issue by shreybothra** [sebp/scikit-survival#258]
I am trying to implement RSF on a dataset i've created. When using get_x_y to split features and labels, y is being returned with only False values even though the dataset contains True values, for Event indicator.

This is the image of the dataset
![Screenshot 2022-04-17 182200](https://user-images.githubusercontent.com/71525149/163716710-b05df0fd-6879-4e45-8daf-0a7f10656300.png)

and here is the screenshot of the code and y values
![Screenshot 2022-04-17 182046](https://user-images.githubusercontent.com/71525149/163716726-46435170-043e-405b-adf9-c7e421084083.png)

I changed the Values in "Censoring" column to '0' for FALSE and '1' for TRUE and it still returns all values as False.

**Comment by sebp** [comment]
I'm guessing you are using pandas's `read_csv` function, which converts "TRUE"/"FALSE" to boolean already. Can you please check what `df.dtypes()` returns?

**Comment by shreybothra** [comment]
Yes, you were right. It is returning Bool. I'm a beginner so I do not know
much. However, when I use Surv.from_dataframe(), i'm getting the right
values for Event indicator, i.e.; TRUE/ FALSE, but with get_x_y as only
FALSE.
