### ISSUE TITLE
Python wheel for pip 

### ISSUE THREAD

**Issue by juancq** [sebp/scikit-survival#259]
**Is your feature request related to a problem? Please describe.**
Release a python wheel for pip (in addition to the existing .tar source).

**Comment by sebp** [comment]
I discovered https://github.com/pypa/cibuildwheel recently, which should do the job, but haven't set it up yet.

**Comment by sebp** [comment]
Please file a new issue with details about your setup for the 
compilation problem.

**Comment by sebp** [comment]
My initial attempt to provide wheels is available to [download](https://github.com/sebp/scikit-survival/suites/6212562078/artifacts/219609487)

It would be very helpful if you could report back whether they work for you.

**Comment by juancq** [comment]
It worked, thanks!
