### ISSUE TITLE
Add return_array argument to CoxPHSurvivalAnalysis().predict_survival_function

### ISSUE THREAD

**Issue by rv-apuri** [sebp/scikit-survival#268]
**Is your feature request related to a problem? Please describe.**
It is mildly frustrating that the predict_survival_function for CoxPHSurvivalAnalysis() does not take in the return_array argument in the same way as RandomSurvivalForest().predict_survival_function does

**Describe the solution you'd like**
```
estimator = CoxPHSurvivalAnalysis().fit(X, y)
survs = estimator.predict_survival_function(X.iloc[:5], return_array=True)
```
`survs` should be an ndarray containing the values from the step function

**Describe alternatives you've considered**
A quick workaround to get the array is below:
```
estimator = CoxPHSurvivalAnalysis().fit(X, y)
funcs = estimator.predict_survival_function(X.iloc[:5])
survs = np.array([f(f.x) for f in funcs])
```

**References and existing implementations**
If you want to propose a new algorithm for inclusion, please include the original reference to the publication that first proposed the algorithm. If you are aware of any existing implementations, e.g. for R, please include a link too.

**Comment by sebp** [comment]
I agree that this would be quite useful.

**Comment by rv-apuri** [comment]
Thank you so much!!
