### ISSUE TITLE
predict_cumulative_hazard_function(X) in CoxPHSurvivalAnalysis return the same function for all entries.

### ISSUE THREAD

**Issue by vfa-phuclkh** [sebp/scikit-survival#27]
I have fitted a CoxPHSurvivalAnalysis model and using that to calculate the Survival function and the Cummulative Hazard function.  
```pred_survival = estimator.predict_survival_function(X_test_tmp)```
The survival function for different entries look quite good like this: 
![surv](https://user-images.githubusercontent.com/36832715/36967523-8f7d55ce-2092-11e8-898a-5fe81a531601.png)

```pred_hazard = estimator.predict_cumulative_hazard_function(X_test_tmp)```
However the cummulative hazard function for all entries are the same: 
![cum_hazard](https://user-images.githubusercontent.com/36832715/36967555-aa5eb3e2-2092-11e8-9e23-387c48d75b89.png)
Any suggestion for this. Thank you.

**Comment by sebp** [comment]
Survival function and cumulative hazard function can be converted into each other, therefore I'm quite surprised to see this result. What's the distribution of the linear predictor (`predict` method)? If you have a minimal example, that would be very helpful as well.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.

**Comment by AndresEspin** [comment]
hi. could you solve that? i'm with thesame issue...
