### ISSUE TITLE
Get the number of iterations needed to train a model

### ISSUE THREAD

**Issue by Genarito** [sebp/scikit-survival#277]
**Is your feature request related to a problem? Please describe.**
I am doing some training time measurements of the `FastKernelSurvivalSVM` model. The problem is that I would like to know how much time it takes for each iteration, but I don't know this amount. It would be nice if the model has the attribute to be able to access it.

**Describe the solution you'd like**
Expose a new attribute (for example, `n_iter`, similarly to modern Scikit-Learn versions, where they [added the n_iter_](https://github.com/scikit-learn/scikit-learn/pull/21408) attribute).

**Describe alternatives you've considered**
I'm accessing the number of iterations through the `optimizer_result_` attribute: 

```python
estimator = FastKernelSurvivalSVM(rank_ratio=0.0, max_iter=1000, tol=1e-5)
# Trains the model...
estimator.optimizer_result_.nit
```

But I'm not really convinced if what I'm doing is right. It'd be cool to have an official solution.

Thanks in advance, this is a great lib :heart:

**Comment by sebp** [comment]
You inferred it correctly, `estimator.optimizer_result_.nit` is what you want (see the [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult) for details).

I agree that having an `n_iter_` attribute would be useful to match sklearn.

**Comment by Genarito** [comment]
Cool! Thank you very much!
