### ISSUE TITLE
Cannot Import "Integrated_Brier_Score"

### ISSUE THREAD

**Issue by nkaur201** [sebp/scikit-survival#284]
Dear Scikit Survival Team, 

Not sure what is missing, but I cannot import the evaluation metric: brier score?  Any help is appreciated. 

![image](https://user-images.githubusercontent.com/36765835/183407172-d72d4189-7d6b-4139-9c38-f986b85a4b88.png)

**Comment by sebp** [comment]
Which version of scikit-survival are you using?

**Comment by nkaur201** [comment]
Hello,  

thank you for getting back! Also, I love the work you have carried out for survival analysis. 

Please the attached image for version

![image](https://user-images.githubusercontent.com/36765835/183472282-16b6f72f-f841-4497-85de-912b7ef92f60.png)

**Comment by sebp** [comment]
integrated_brier_score has been added in 0.13. Therefore, you would need 
to upgrade.

**Comment by nkaur201** [comment]
I see - thank you so much!
