### ISSUE TITLE
Error when implementing Integrated Brier Score 

### ISSUE THREAD

**Issue by nkaur201** [sebp/scikit-survival#287]
Dear Scikit-survival Team, 

I am struggling to implement the integrated brier score by following the tutorial. 

I get the error: "ValueError expected estimate with 7317 samples but got 9"

x_test = 7317 samples. 

Any guidance is greatly appreciated! 

I have shared my code: 

![image](https://user-images.githubusercontent.com/36765835/184384303-7b8f0e17-f1d8-4e0f-b511-548c1fb5a1d7.png)

**Comment by sebp** [comment]
You should pass `random_survival_prob` directly to `integrated_brier_score` without the for loop.

**Comment by nkaur201** [comment]
![image](https://user-images.githubusercontent.com/36765835/184603531-3c99149f-e518-4b8f-adcb-f8f01e8f5ac4.png)

Thank you!
