### ISSUE TITLE
Kaplan Meier output consistent regardless of time

### ISSUE THREAD

**Issue by thatemmagirl** [sebp/scikit-survival#29]
Very useful article, thanks guys. I'm having problems getting the Kaplan Meier Estimator to give a meaningful output. I've saved my results in a record array as shown below, with the event of a cancellation happening as boolean and the number of days before cancellation / number of days so far if there has not yet been a cancellation as a float. I don't understand why the kaplan meier estimaor always predicts the cancellations to be at a steady rate of one regardless of the time, and I don't have the code for the Kaplan Meier Estimator to check. Has anyone else had this problem and how can it be solved? 
![image](https://user-images.githubusercontent.com/37808555/37917255-d2068b84-3115-11e8-9b75-d2816400074d.png)

**Comment by pavopax** [comment]
I tried to reproduce your problem but couldn't.

- [ ] can you print version of sksurv (`import sksurv as sks; sks.__version__`)?
- [ ] Can you restart your kernel, then try the following snippet and paste the output?

```python
%matplotlib inline
import matplotlib.pyplot as plt
from sksurv.nonparametric import kaplan_meier_estimator

import pandas as pd

df = pd.DataFrame(
    {'Canc': [False, False, True, False, True, False],
     'days': [693, 298, 52, 365, 361, 307]})
y = df.to_records(index=False)

time, survival_prob = kaplan_meier_estimator(y["Canc"], y["days"])
plt.step(time, survival_prob, where="post");
```

![screen shot 2018-03-26 at 9 41 45 am](https://user-images.githubusercontent.com/6165713/37919839-ee9cfe54-30d9-11e8-8cec-8ddfedd94bff.jpg)

**Comment by thatemmagirl** [comment]
Interesting - when trying to print the version on sksurv it states 'unknown'. I think this is because I had to add a line of code '# coding: utf-8' to the top of the .py file 'nonparametric' in the package to fix this error:
![image](https://user-images.githubusercontent.com/37808555/37954598-361033ea-319e-11e8-80cd-145d59bc9a4c.png)

have you seen this error before? If so, what did you do to deal with it?

When I copied in your code I got this:
![image](https://user-images.githubusercontent.com/37808555/37954660-645dedc8-319e-11e8-9e70-c994ed647b8c.png)

**Comment by sebp** [comment]
Adding `# coding: utf-8` should not be necessary with Python 3, which handles utf-8 encoded files by default, which suggests you are mixing Python 2 and 3.

Could please post more details about your setup, please:
- How did you install scikit-survival?
- What's your Python version?
- What's your numpy version?
- What's your scipy version?
- What's your matplotlib version?

You can use `pandas.show_versions()`.

**Comment by thatemmagirl** [comment]
My python version is 2.7
Numpy version is 1.13.1
Scipy version is 0.19.1
Matplotlib version is  1.5.3

I do not have administrative rights on my computer so someone else downloaded scikit-survival for me but I'm assuming they installed it using pip.

**Comment by sebp** [comment]
Python 2 is not supported, only Python 3. Could you please try your example in a Python 3 environment?

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
