### ISSUE TITLE
ValueError: censoring survival function is zero at one or more time points

### ISSUE THREAD

**Issue by saurabhbidwai** [sebp/scikit-survival#294]
I'm getting this error after changing my dependent variable i.e resp_days, earlier its was working totally fine, can anyone help how to get a rid of it. Thanks in advance.

**Comment by sebp** [comment]
When reporting a bug, please follow the [instructions](https://github.com/sebp/scikit-survival/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and include a detailed description of the problem and a minimal working example please.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
