### ISSUE TITLE
During install: error: command '/usr/bin/clang' failed with exit code 1

### ISSUE THREAD

**Issue by tpilewicz** [sebp/scikit-survival#303]
Python version: Python 3.10.3

OS: OSX 12.4  (Proc: M1 chip)

When trying to pip install (tried versions 0.17 and 0.18):

```
      222 warnings and 4 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

The errors seem to be:

```
      In file included from sksurv/linear_model/_coxnet.cpp:801:
      In file included from sksurv/linear_model/src/coxnet_wrapper.h:21:
      sksurv/linear_model/src/coxnet/coxnet.h:139:23: error: expected unqualified-id
                  if (!std::isfinite(exp_xw[k])) {
                            ^
```

__________

```
      In file included from sksurv/linear_model/src/coxnet/coxnet.h:18:
      In file included from sksurv/linear_model/src/eigen/Eigen/Core:374:
      sksurv/linear_model/src/eigen/Eigen/src/Core/MathFunctions.h:753:12: error: reference to unresolved using declaration
          return isnan EIGEN_NOT_A_MACRO (x);
                 ^
```

______

```
      In file included from sksurv/linear_model/src/coxnet/coxnet.h:18:
      In file included from sksurv/linear_model/src/eigen/Eigen/Core:374:
      sksurv/linear_model/src/eigen/Eigen/src/Core/MathFunctions.h:738:12: error: reference to unresolved using declaration
          return isinf EIGEN_NOT_A_MACRO (x);
                 ^
```

________

```
      In file included from sksurv/linear_model/src/coxnet/coxnet.h:18:
      In file included from sksurv/linear_model/src/eigen/Eigen/Core:374:
      sksurv/linear_model/src/eigen/Eigen/src/Core/MathFunctions.h:723:12: error: reference to unresolved using declaration
          return isfinite EIGEN_NOT_A_MACRO (x);
                 ^
```

Happy to provide more details if needed

**Comment by sebp** [comment]
Unfortunately, I don't have access to an M1 Mac to test. My wild guess is that some headers are missing, see https://apple.stackexchange.com/a/337945

**Comment by tpilewicz** [comment]
Thanks for the answer. You mean flags that would enable the import of `isfinite` / `isinf`?

**Comment by sebp** [comment]
My guess is that some header files are missing that contain the defintion for `isfinite` / `isinf`.

**Comment by sebp** [comment]
Alternatively, you could try moving `#include <cmath>` before `#include <Eigen/Core>`:

https://github.com/sebp/scikit-survival/blob/6b64676c6a410146f3a615fe80ec7b16a0502ecc/sksurv/linear_model/src/coxnet/coxnet.h#L18-L21

**Comment by tpilewicz** [comment]
I tried your suggestion, it didn't seem to work 😕 

But when I `python setup.py install`, I can see that the generated `clang` command is:

```
building 'sksurv.linear_model._coxnet' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Users/pilewicz/.pyenv/versions/jup310/lib/python3.10/site-packages/numpy/core/include -Isksurv/linear_model/src -Isksurv/linear_model/src/eigen -I/Users/pilewicz/.pyenv/versions/jup310/include -I/Users/pilewicz/.pyenv/versions/3.10.3/include/python3.10 -c sksurv/linear_model/_coxnet.cpp -o build/temp.macosx-12.1-arm64-cpython-310/sksurv/linear_model/_coxnet.o -std=c++14
```

If I manually run:

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/pilewicz/.pyenv/versions/jup310/lib/python3.10/site-packages/numpy/core/include -Isksurv/linear_model/src -Isksurv/linear_model/src/eigen -I/Users/pilewicz/.pyenv/versions/jup310/include -I/Users/pilewicz/.pyenv/versions/3.10.3/include/python3.10 -c sksurv/linear_model/_coxnet.cpp -o build/temp.macosx-12.1-arm64-cpython-310/sksurv/linear_model/_coxnet.o -std=c++14
```

(so without `12.1` before `.sdk`) It seems to work. But I don't understand what generates the `clang` flags

**Comment by sebp** [comment]
Ok, that means the path to the headers is wrong.

Could you try if running `export SDKROOT=$(xcrun --show-sdk-path --sdk macosx)` prior to installing scikit-surviva?

**Comment by tpilewicz** [comment]
Thanks for the help. Unfortunately, same error 😕 

This didn't seem to change the `clang` command:

```
building 'sksurv.linear_model._coxnet' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Users/pilewicz/.pyenv/versions/jup310/lib/python3.10/site-packages/numpy/core/include -Isksurv/linear_model/src -Isksurv/linear_model/src/eigen -I/Users/pilewicz/.pyenv/versions/jup310/include -I/Users/pilewicz/.pyenv/versions/3.10.3/include/python3.10 -c sksurv/linear_model/_coxnet.cpp -o build/temp.macosx-12.1-arm64-cpython-310/sksurv/linear_model/_coxnet.o -std=c++14
```

Although if I echo `SDKROOT`:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

**Comment by sebp** [comment]
Let's try

```bash
CPPFLAGS="-isysroot $(xcrun --show-sdk-path --sdk macosx)" python setup.py install
```

**Comment by tpilewicz** [comment]
Also something odd: I just tried to run clang without any of the SDK paths:

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall \
  -I/Users/pilewicz/.pyenv/versions/jup310/lib/python3.10/site-packages/numpy/core/include \
  -Isksurv/linear_model/src \
  -Isksurv/linear_model/src/eigen \
  -I/Users/pilewicz/.pyenv/versions/jup310/include \
  -I/Users/pilewicz/.pyenv/versions/3.10.3/include/python3.10 \
  -c sksurv/linear_model/_coxnet.cpp -o build/temp.macosx-12.1-arm64-cpython-310/sksurv/linear_model/_coxnet.o -std=c++14
```

and it worked as well 🤔 

Trying your suggestion now

**Comment by tpilewicz** [comment]
So I just ran your suggestion: `CPPFLAGS="-isysroot $(xcrun --show-sdk-path --sdk macosx)" python setup.py install`

And same error. But the clang command got affected, it did include your `-isysroot` option:

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall \
  -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include \
  -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include \
  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
  -I/Users/pilewicz/.pyenv/versions/jup310/lib/python3.10/site-packages/numpy/core/include \
  -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include \
  -Isksurv/linear_model/src -Isksurv/linear_model/src/eigen \
  -I/Users/pilewicz/.pyenv/versions/jup310/include \
  -I/Users/pilewicz/.pyenv/versions/3.10.3/include/python3.10 \
  -c sksurv/linear_model/_coxnet.cpp -o build/temp.macosx-12.1-arm64-cpython-310/sksurv/linear_model/_coxnet.o -std=c++14
```

It seems the issue is not that I have to include from `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`, but rather that I must not include from `/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include`

**Comment by tpilewicz** [comment]
After some digging with a debugger, the offending flags are added by distutils with this line: https://github.com/pypa/distutils/blob/3c50821d74f4ced3f5331d16eba7d570a8dd2360/distutils/command/build_ext.py#L316

distutils is adding some flags present in `sysconfig.get_config_vars()["CFLAGS"]`

When I switch my `pyenv` to another version of python, the content for these `CFLAGS` changes and the problematic `12.1` is removed. So I guess this could be related with [this issue from pyenv](https://github.com/pyenv/pyenv/issues/2204)

**Comment by sebp** [comment]
I see. Then your only option might be to create symlink such that `/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/` points to `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`.

**Comment by tpilewicz** [comment]
Well, since the pyenv issue implied that the CFLAGS were leaked at the moment of building python, I just reinstalled my python 3.10 (which was the only one containing faulty CFLAGS), and they're now correct. I am now able to `pip install scikit-survival` regularly

Thanks a lot for helping debug!
