### ISSUE TITLE
Generating concordance index vs alpha plot (CoxnetSurvivalAnalysis)

### ISSUE THREAD

**Issue by mzhao94** [sebp/scikit-survival#31]
Do you by any chance have the full code to generate the graph on the 13th slide of this presentation?

https://k-d-w.org/slides/pyconuk-2017/

I tried to replicate the code on slide 12 but it doesn't converge and also doesn't show how to calculate the concordance index for each of the alphas. Was this done manually with code that's not yet incorporated into scikit-survival? If so, would you be able to share the code? 

Any help would be much appreciated.

**Comment by Lesskin** [comment]
@mzhao94 Hello ! I'm trying to do the same as you and I'm getting the same error, however I cannot figure out how to bypass it. 

Could you maybe share a bit of your code that would be incredibly helpful and your help will be worship for years to come !

**Comment by sebp** [comment]
I uploaded an example at https://gist.github.com/sebp/d580d44c4beab3379c6dfda6810b33b8
