### ISSUE TITLE
raise ValueError during leave one out cross validation

### ISSUE THREAD

**Issue by hellorp1990** [sebp/scikit-survival#310]
Hi,

I am having an error during leave one out cross-validation (raise ValueError("Need a minimum of two samples")). I commented out the two 'if' comments but still it resulted in an error.

During leave-one-out cross-validation testing there will be one sample only, so how can I do that or is it possible with the current settings of this repo? 

Thank you in advance.

**Comment by sebp** [comment]
Which model are trying to fit? If it's a survival SVM, you cannot do prediction based on a single sample.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
