### ISSUE TITLE
Suggestions for StepFunction

### ISSUE THREAD

**Issue by drproduck** [sebp/scikit-survival#321]
I have 2 minor suggestions for StepFunction that I would like to see:

1. Different argument name for 'x' in __init__ and __call__. In addition, current API reference is missing.
2. Sort the arrays inside the function.

Thanks.

**Comment by sebp** [comment]
The API reference is available: https://scikit-survival.readthedocs.io/en/latest/api/generated/sksurv.functions.StepFunction.html

1. What's wrong with `x`? What are you suggesting to use as an alternative?
2. You shouldn't be required to create a StepFunction instance yourself, therefore I can't see a setting where sorting might be required.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
