### ISSUE TITLE
Problem in the concordance metric

### ISSUE THREAD

**Issue by 7belrhalmia** [sebp/scikit-survival#33]
Hello,
The concordance metric give me this error.

![image](https://user-images.githubusercontent.com/13202562/40730302-9db72b76-642e-11e8-9da2-79f31be29038.png)

Regards.

**Comment by sebp** [comment]
Could you provide a minimal example to reproduce this error, please?

**Comment by 7belrhalmia** [comment]
@sebp you mean the data set and the notebook.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
