### ISSUE TITLE
problem when run setup.py install

### ISSUE THREAD

**Issue by ldw2013** [sebp/scikit-survival#34]
hi when I was using the command 'python setup.py install', there has a lookup error

it shows that

setuptools-scm was unable to detect version for ...

Make sure you are either building from a fully intact git repository or PyPI tarballs...

Has anyone got the same problem with me? and could anyone give me some hint on how to fix the bug?

Thanks in advance

**Comment by sebp** [comment]
How did you download the source code? When installing from source you 
need to clone the git repository (check that you have a .git folder).

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
