### ISSUE TITLE
Survival Data sources

### ISSUE THREAD

**Issue by bhavikajalli** [sebp/scikit-survival#35]
Hello,
Could you point me to some survival datasets on machines or equipment or even a webpage that I can scrape the details from?

**Comment by sebp** [comment]
Some datasets are [included](https://scikit-survival.readthedocs.io/en/latest/api.html#datasets). For additional resources, have a look at [datasets from the book Modeling Survival Data](https://www.mayo.edu/research/departments-divisions/department-health-sciences-research/division-biomedical-statistics-informatics/terry-m-therneau-phd-additional-information/additional-materials-book) and http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets. The latter is not specific to survival analysis and contains links to other sites as well.
