### ISSUE TITLE
Evaluate multiple metrics with a single GridSearchCV

### ISSUE THREAD

**Issue by caaperezag** [sebp/scikit-survival#351]
**Describe the bug**

Kind regards,

Currently, I am doing a simulation to compare multiple models, my study doesn't require the `best_estimator_` only the results from `cv_results_`. The problem that I have is that I need the `integrated_brier_score` and `cumulative_dynamic_auc` for each combination of hyperparameters. As far as I know, I can't use `sksurv.metrics.as_cumulative_dynamic_auc_scorer` and `sksurv.metrics.as_integrated_brier_score_scorer` together to get from the same fit.

**Code Sample to Reproduce the Bug**

```python
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.feature_selection import SelectKBest
from sklearn.pipeline import Pipeline
from sksurv.datasets import load_veterans_lung_cancer
from sksurv.preprocessing import OneHotEncoder
from sksurv.linear_model import CoxnetSurvivalAnalysis
from sksurv.metrics import integrated_brier_score, cumulative_dynamic_auc
from sklearn.metrics import make_scorer

import pandas as pd

data_x, data_y = load_veterans_lung_cancer()

pipe = Pipeline([('encode', OneHotEncoder()),
                 ('model', CoxnetSurvivalAnalysis(fit_baseline_model=True))])

param_grid = {'model__l1_ratio': [i/10 for i in range(1, 11)]}
cv = KFold(n_splits=3, random_state=1, shuffle=True)
gcv = GridSearchCV(pipe, param_grid, return_train_score=True, cv=cv, 
                   refit = False,
                   scoring={"integrated_brier_score": make_scorer(integrated_brier_score), 
                            "cumulative_dynamic_auc": make_scorer(cumulative_dynamic_auc)})
gcv.fit(data_x, data_y)

results = pd.DataFrame(gcv.cv_results_)
```

**Expected Results**
The result for each combination of hyperparameters and metrics

**Actual Results**
return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
TypeError: integrated_brier_score() missing 2 required positional arguments: 'estimate' and 'times'

**Versions**
Please execute the following snippet and paste the output below.

System:
    python: 3.9.15 (main, Nov 11 2022, 13:58:57)  [GCC 11.2.0]
executable: [/home/carlos/intel/oneapi/intelpython/latest/envs/pytorch/bin/python](https://vscode-remote+ssh-002dremote-002bintel1.vscode-resource.vscode-cdn.net/home/carlos/intel/oneapi/intelpython/latest/envs/pytorch/bin/python)
   machine: Linux-5.15.104-2-MANJARO-x86_64-with-glibc2.37

Python dependencies:
          pip: 22.2.2
   setuptools: 63.4.1
      sklearn: 1.0.1
        numpy: 1.22.3
        scipy: 1.7.3
       Cython: None
       pandas: 1.5.1
   matplotlib: 3.7.1
       joblib: 1.2.0
threadpoolctl: 3.1.0

Built with OpenMP: True
sksurv: 0.0.0
[/home/carlos/intel/oneapi/intelpython/latest/envs/pytorch/lib/python3.9/site-packages/_distutils_hack/__init__.py:33](https://vscode-remote+ssh-002dremote-002bintel1.vscode-resource.vscode-cdn.net/home/carlos/intel/oneapi/intelpython/latest/envs/pytorch/lib/python3.9/site-packages/_distutils_hack/__init__.py:33): UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```

Thanks.

**Comment by sebp** [comment]
@caaperezag I didn't have this use case in mind. Currently, the recommended way is to use `as_integrated_brier_score_scorer` (or similar) to override the estimator's `score` method. Unfortunately, this also means you cannot have two metrics concurrently (there can only be one `score` method).

sklearn's `make_scorer` doesn't work, because `make_scorer` assumes metrics can be computed from the prediction and true label, but for survival metrics, access to dataset's survival times – to estimate the censoring distribution from – are required too.
