### ISSUE TITLE
Add support for pandas 0.23

### ISSUE THREAD

**Issue by badge** [sebp/scikit-survival#36]
pandas 0.23 isn't supported by scikit-survival version 0.5. I've made a start at identifying necessary changes here: https://github.com/badge/scikit-survival/commit/9f050bbd0453286deb1ae7f8896de8f93019e101

Currently, I'm having a problem with the nosetests where the `TestOneHotEncoder` class (and others?) expects `pandas.DataFrame.select_dtypes` to return a DataFrame whose columns are ordered alphabetically instead of reflecting their original location, so there are assertListEqual tests failing. I can't see that this has ever been the case in pandas, so I'm confused!

The `reduce` argument has been deprecated in `pandas.DataFrame.apply`, so the last line of `table.apply(transform, axis=0, reduce=False)` currently raises a `DeprecationWarning`.

**Comment by sebp** [comment]
Thanks for your efforts in adding support for pandas 0.23. I haven't checked the change log for pandas 0.23 yet, but pandas 0.22 does work fine (currently in the npy114 branch). The tricky part is to support 0.23 as well as previous version of pandas. I tried to avoid constructing data frames from dictionaries, because that resulted in columns being ordered randomly. The behaviour improved with recent versions of pandas and python, so I'm not sure what is going on. If you can point me to a specific test that is failing, I can take a look.

**Comment by badge** [comment]
I've found the solution to the particular issue I was having, and identified one in the introductory notebook (https://nbviewer.jupyter.org/github/sebp/scikit-survival/blob/master/examples/00-introduction.ipynb).

CPython 3.6 maintains insertion order for dictionaries by default (I'm pretty sure all other distributions too, and from Python 3.7 is in the language spec). As you said, constructing DataFrames from dictionaries can cause random ordering of the columns. I updated the instances of `from_items` to `from_dict`, but used `OrderedDict` from the `collections` module to maintain backward compatibility with Python <3.6. What I missed, however, was the `dat_cat = pd.DataFrame(dict(...` in `test_preprocessing.py`, which looks to me like an error. If you run this in Python 3.5, `TestOneHotEncoder.test_fit` will likely pass because

    self.assertListEqual(t.feature_names_.tolist(),
                         ['binary_1', 'binary_2', 'many', 'trinary']

will pass--the feature names will be returned in alphabetically order. What I can't work out is why your Travis tests pass--this is exactly what failed for me!

I've made the necessary changes (including adding `packaging` as a requirement for checking the Pandas version in `column.py` to https://github.com/badge/scikit-survival/commit/a7ed05ba68a8a170c7325fa3e61eb1a20f0af6f4.

Finally, the example notebook doesn't work on Python 3.6 because the columns of `data_x` and `data_x_numeric` aren't ordered alphabetically, but the definition of `x_new` assumes that they are.

**Comment by badge** [comment]
I've created a new branch--pandas23 at https://github.com/badge/scikit-survival/tree/pandas23.

**Comment by sebp** [comment]
I rebased your branch on top of latest master and fixed a couple of issues, tests are fine now. Changes are in the [pandas23 branch](https://github.com/sebp/scikit-survival/tree/pandas23).

**Comment by sebp** [comment]
Actually, I realised that several tests with pandas 0.23 are failing, see https://travis-ci.org/sebp/scikit-survival/jobs/400060402

**Comment by badge** [comment]
That was a bit daft of me! Glad to see your commits fixed it. :smile:
