### ISSUE TITLE
Out of date pandas function calls (iteritems vs items).

### ISSUE THREAD

**Issue by iraxter** [sebp/scikit-survival#372]
**Describe the bug**

A number of the internal sksurv functions use iteritems() on dataframes which is no longer supported by pandas 2+. Looks like pyproject.toml notes this and attempts to suppress warnings but I was still receiving warnings when using pandas 1.5.3 (code would not run on pandas 2+ versions)

Grepping the codebase looks like column.py, arffwrite.py, util.py, conftest.py, test_io.py, and test_preprocessing.py all use iteritems(), could those be changed to items() instead?

**Comment by sebp** [comment]
Currently, pandas 2 is not supported. Changing `iteritems()` to `items()` and requiring pandas >= 1.0 is certainly possible.
