### ISSUE TITLE
Random forest survival for feature selection? 

### ISSUE THREAD

**Issue by kimrants** [sebp/scikit-survival#38]
It seems that there should be an implementation of ensemble methods, but I cannot seem to find the documentation for this? How can I make this work? 
Thank you!

**Comment by sebp** [comment]
Random survival forest are currently not implemented, the only ensemble models part of scikit-survival are based on [gradient boosting](https://scikit-survival.readthedocs.io/en/latest/api.html#ensemble-models). They do have a `feature_importances_` attribute that you can use.
