### ISSUE TITLE
conf_type is not working in kaplan_meier_estimator:

### ISSUE THREAD

**Issue by raminsalmas** [sebp/scikit-survival#384]
**Describe the bug**

**Code Sample to Reproduce the Bug**

```python
# Insert your code here that produces the bug.
# This example should be as succinct as possible and self-contained,
# i.e., not rely on external data.
# We are going to copy-paste your code and we expect to get the same result as you.
# It should run in a fresh python session, and so include all relevant imports.
```

**Expected Results**

**Actual Results**
Please paste or specifically describe the actual output or traceback.

**Versions**
Please execute the following snippet and paste the output below.

```python
import sklearn; sklearn.show_versions()
import sksurv; print("sksurv:", sksurv.__version__)
import cvxopt; print("cvxopt:", cvxopt.__version__)
import cvxpy; print("cvxpy:", cvxpy.__version__)
import numexpr; print("numexpr:", numexpr.__version__)
import osqp; print("osqp:", osqp.OSQP().version())
```
kaplan_meier_estimator is not working with conf_type. Is that something with the version of the code?

**Comment by sebp** [comment]
Thanks for reporting this issue. Could you please elaborate on what "is 
not working" means exactly, provide a code example and the the version 
information.

**Comment by raminsalmas** [comment]
Thanks. I was on the incorrect version, and it has already been sorted out.
