### ISSUE TITLE
plotting a tree from estimators_[i] from RandomSurvivalForest.fit()

### ISSUE THREAD

**Issue by guangyueyeh** [sebp/scikit-survival#394]
I got an error message: 'SurvivalTree' object has no attribute 'criterion'
when using export_graphviz to plot a tree from estimators_[i] from RandomSurvivalForest.fit() 

export_graphviz(estimator, out_file='tree.dot', 
                feature_names = feature_names,
                class_names = target_names,
                rounded = True, proportion = False, 
                precision = 2, filled = True)

**Comment by sebp** [comment]
Can you please provide version information as described in the [issue template](https://github.com/sebp/scikit-survival/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by guangyueyeh** [comment]
snippet code:
import sklearn; sklearn.show_versions()
import sksurv; print("sksurv:", sksurv.__version__)
import cvxopt; print("cvxopt:", cvxopt.__version__)
import cvxpy; print("cvxpy:", cvxpy.__version__)
import numexpr; print("numexpr:", numexpr.__version__)
import osqp; print("osqp:", osqp.OSQP().version())


outputs:
System:
    python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
executable: c:\users\yeh_g\appdata\local\programs\python\python39\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
      sklearn: 1.2.2
          pip: 23.1.2
   setuptools: 68.0.0
        numpy: 1.21.5
        scipy: 1.8.0
       Cython: 0.29.35
       pandas: 1.4.1
   matplotlib: 3.5.1
       joblib: 1.2.0
threadpoolctl: 3.1.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
         prefix: libopenblas
       filepath: C:\Users\yeh_g\AppData\Local\Programs\Python\Python39\Lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
        version: 0.3.17
threading_layer: pthreads
   architecture: SkylakeX
    num_threads: 8

       user_api: openmp
   internal_api: openmp
         prefix: vcomp
       filepath: C:\Users\yeh_g\AppData\Local\Programs\Python\Python39\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None
    num_threads: 8

       user_api: blas
   internal_api: openblas
         prefix: libopenblas
       filepath: C:\Users\yeh_g\AppData\Local\Programs\Python\Python39\Lib\site-packages\scipy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
        version: 0.3.17
threading_layer: pthreads
   architecture: SkylakeX
    num_threads: 8
sksurv: 0.20.0
cvxopt: 1.3.1
cvxpy: 1.3.2
numexpr: 2.8.4
osqp: 0.6.2

**Comment by sebp** [comment]
Can you please try if upgrading to scikit-survival 0.21 fixes it for you?

**Comment by guangyueyeh** [comment]
After upgranding to scikit-survival 0.21.0
and then executed export_graphviz as below:
export_graphviz(estimator, out_file='tree.dot', 
                feature_names = feature_names,
                class_names = target_names,
                filled=True, rounded = True,
                proportion = False, precision = 2,
                rotate=True)

I got a different error message:
ValueError: cannot convert float NaN to integer

**Comment by sebp** [comment]
You have to use `filled=False`

**Comment by guangyueyeh** [comment]
It works now.  Thank you very much.
