### ISSUE TITLE
Possible memory leak for FastKernelSurvivalSVM

### ISSUE THREAD

**Issue by glgmartin** [sebp/scikit-survival#398]
I have been using a FastKernelSurvivalSVM on one of my own datasets and I noticed a very high use of RAM.
Here are a few details of the tests I performed:
* dataset shape is 100K rows by 32 cols, with most of them resulting from a previous one hot encoding step
* first tests on my laptop used all 32Gos of RAM, I stopped it before it could converge
* I conducted a second test on a server and used 200Gos of RAM for fitting a single instance of the model on this dataset

Sadly, I cannot share the exact dataset for privacy reasons.
sksurv version is 0.21.0.

Could this behevior be linked to a possible memory leak in the model or in the optimizers? Or simply because of the dataset size (taking into account that SVM need to see all the data iirc).

Thanks!

**Comment by sebp** [comment]
Kernel-based methods, such as `FastKernelSurvivalSVM`, will require creating a matrix quadratic in the size of the number of samples. In your case it will have 10^10 entries and require about 74GB of space.

While there are ways to avoid having to pre-compute the entire matrix, it is not something that I'm going to implement.
