### ISSUE TITLE
Example using `predict()`

### ISSUE THREAD

**Issue by btengels** [sebp/scikit-survival#4]
More of a feature request than an issue, but I'm trying to use sksurv for some predictive modeling and am having a hard time interpreting the `predict` output for most of the estimators. For example, with `GradientBoostingSurvivalAnalysis` the `predict(X)` output is described as the hazard for X. The output from my test data, however, is often negative which doesn't make sense for a traditional hazard rate. Is there any way to include a `predict` step in your current example notebook?

More than anything, I would like to be able to predict the survival duration of items not in my training data (like the `predict_expected in the lifelines library`). If that functionality doesn't exist, I would be happy to submit a pull request to that end if you can advise me a bit on how to interpret the current `predict` output. 

And a million thanks for making this code available and easy to install/use. This is cool stuff!

**Comment by sachanganesh** [comment]
I agree with @btengels.

I'm a novice with survival analysis, so I found it hard to interpret predictions from different models. I actually had the exact same issue with the `GradientBoostingSurvivalAnalysis` model.

Thanks a bunch!

**Comment by fritshermans** [comment]
Unfortunately, the link to the coxph-survival-function does not work. Could you please give us some hints on how to get predictions for survival duration?

**Comment by sebp** [comment]
The branch has been merged, have a look at [Introduction to Survival Analysis with scikit-survival ](https://nbviewer.jupyter.org/github/sebp/scikit-survival/blob/master/examples/00-introduction.ipynb).
