### ISSUE TITLE
Description of estimate parameter in integrated_brier_score is unclear

### ISSUE THREAD

**Issue by anonym-ai** [sebp/scikit-survival#414]
**Description**

There is a contradiction in the documentation and in the used example.

for integrated_brier_score function, the estimate argument is described as an array of the risk at a given time of experiencing an event
https://github.com/sebp/scikit-survival/blob/32ae49b51865e1aecf72d0bf87c64e735bf5d548/sksurv/metrics.py#L666

in the documentation of the example, the estimate argument is survival probability array. quite the opposite.
https://github.com/sebp/scikit-survival/blob/32ae49b51865e1aecf72d0bf87c64e735bf5d548/sksurv/metrics.py#L702

I would expect either `preds=1 - survs` or `preds = model.cumulative_hazard_function`.
Am I missing something ?

I thing clarification should also be done in other metrics.

```
SYSTEM
------
Platform          : Linux-5.13.0-52-generic-x86_64-with-glibc2.31
Python version    : CPython <module 'platform' from '/usr/lib/python3.10/platform.py'>
Python interpreter: /usr/bin/python

DEPENDENCIES
------------
sksurv            : 0.21.0
sklearn           : 1.2.2
numpy             : 1.22.4
scipy             : 1.10.1
pandas            : 1.5.0
numexpr           : 2.8.5
ecos              : 2.0.12
osqp              : 0.6.3
joblib            : 1.2.0
matplotlib        : 3.6.0
pytest            : 6.2.5
sphinx            : None
Cython            : 0.29.32
/usr/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
pip               : 22.3.1
setuptools        : 65.4.1
```

**Comment by sebp** [comment]
I agree that "risk" is a bad description. The second sentence has it right:#
>  the estimated probability of remaining event-free

**Comment by anonym-ai** [comment]
The whole parameter description paragraph is contradicting himself for this function.
https://github.com/sebp/scikit-survival/blob/32ae49b51865e1aecf72d0bf87c64e735bf5d548/sksurv/metrics.py#L666

```
    estimate : array-like, shape = (n_samples, n_times)
        Estimated risk of **experiencing an event for test data** at `times`.
        The i-th column must contain the estimated probability of
        **remaining event-free up** to the i-th time point.

```
