### ISSUE TITLE
Description of estimate parameter in brier_score is unclear

### ISSUE THREAD

**Issue by juliusge** [sebp/scikit-survival#416]
I think the first sentence of the estimate input descriptions in the **brier score / ibs functions** is misleading: 

`estimate: Estimated risk of experiencing an event for test data at times.
        The i-th column must contain the estimated probability of
        remaining event-free up to the i-th time point.
`
( https://github.com/sebp/scikit-survival/blob/86cab235af646c8028fead71c6ecab40eb3ec1f7/sksurv/metrics.py#L548C8-L548C8 )

One could rather phrase it `Estimated probability of not experiencing an event` or `1 - estimated risk of experiencing an event`.

**Comment by sebp** [comment]
Thanks for helping to improve scikit-survival.

Could your please elaborate which part you consider confusing and why, please?

**Comment by juliusge** [comment]
Thanks for getting back! 
The brier score functions take as estimate input the probability for the negative class while the other metrics take the probability (or score) for the positive class (=event). The first line describing the `estimate`, however, is the same: `estimate: Estimated risk of experiencing an event for test data`. I would then believe, that a high estimate should - consistently with AUC_C,D - correspond to the positive class. However, reading the second sentence then clarifies that it is actually the other way around: `The i-th column must contain the estimated probability of remaining event-free up to the i-th time point.`

I thought the two sentences are unnecessarily ambiguous and could lead to some confusion.

**Comment by anonym-ai** [comment]
Duplicate with https://github.com/sebp/scikit-survival/issues/414 i guess

**Comment by sebp** [comment]
Fixed in #424
