### ISSUE TITLE
Different results of CoxPHSurvivalAnalysis and CoxnetSurvivalAnalysis

### ISSUE THREAD

**Issue by leihuang** [sebp/scikit-survival#42]
The documentation of `CoxPHSurvivalAnalysis` says: 
> Cox proportional hazards model.

And the documentation of `CoxnetSurvivalAnalysis` says:
> Cox's proportional hazard's model with elastic net penalty.

So I assume the two classes implement the same model, and should return the same results when set with the same model parameters and given the same data. However, I see different results. Why? Also, what are the differences between them?

Codes:
```python
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.datasets import load_veterans_lung_cancer
from sksurv.preprocessing import OneHotEncoder

X_, y = load_veterans_lung_cancer()
X = OneHotEncoder().fit_transform(X_)

# try to match the model parameters wherever possible
f = CoxPHSurvivalAnalysis(alpha=0.5, n_iter=100000)
g = CoxnetSurvivalAnalysis(alphas=[0.5], alpha_min_ratio=1, n_alphas=1, 
                           l1_ratio=1e-16, tol=1e-09, normalize=False)

print(f)
print(g)

f.fit(X, y)
g.fit(X, y)

print(f.coef_)
print(g.coef_[:,0])
```

Output:
```python
CoxPHSurvivalAnalysis(alpha=0.5, n_iter=100000, tol=1e-09, verbose=0)
CoxnetSurvivalAnalysis(alpha_min_ratio=0.0001, alphas=[0.5], copy_X=True,
            l1_ratio=1e-16, max_iter=100000, n_alphas=1, normalize=False,
            penalty_factor=None, tol=1e-09, verbose=False)
[-8.34518623e-03 -7.21105070e-01 -2.80434400e-01 -1.11234345e+00
 -3.26083027e-02 -1.93213436e-04  6.22726190e-02  2.90289950e-01]
[-0.00346722 -0.05117406  0.06044394 -0.16433136 -0.03300373  0.0003172
 -0.00881617  0.06956854]
```

What I've gathered:
* `CoxPHSurvivalAnalysis` is `sksurv`'s own implementation of Cox Proportional Hazard model, and supports ridge (L2) regularization. 
* `CoxnetSurvivalAnalysis` is a wrapper of some C++ extension codes used by R's `glmnet` package, and supports elastic net (L1 and L2) regularization. 
* In the test files, `CoxPHSurvivalAnalysis` is tested with the Rossi dataset, while `CoxnetSurvivalAnalysis` is tested with the Breast Cancer dataset. 
* The two classes have different constructor signatures and methods (eg, only `CoxPHSurvivalAnalysis` has `predict_survival_function`). 

Will it be some nice features to have a consolidated constructor signatures and methods for the two classes? And have them tested on the same dataset, for validation or comparison? 

Thanks.

**Comment by sebp** [comment]
`CoxPHSurvivalAnalysis` and `CoxnetSurvivalAnalysis` are related but do not implement the same model. As you summarized, the difference is in penalty terms. Thus, the coefficients found by `CoxPHSurvivalAnalysis` and `CoxnetSurvivalAnalysis` will differ. In addition, `CoxnetSurvivalAnalysis` supports fitting a path of coefficients for varying penalization strength `alpha` without much computational overhead. `CoxPHSurvivalAnalysis` will only return the result for a single a penalization strength `alpha` only. This is the main reason why constructors differ.

The fact that `predict_survival_function` is not available for `CoxnetSurvivalAnalysis` is an oversight which should be corrected.

**Comment by sebp** [comment]
You cannot completely eliminate the l1 penalty in `CoxnetSurvivalAnalysis`, thus you aren't able to exactly match the result of `CoxnetSurvivalAnalysis`.

**Comment by leihuang** [comment]
By referencing the `scikit-learn` documentation (eg, see [here](https://stackoverflow.com/questions/47365978/scikit-learn-elastic-net-approaching-ridge/52281747)) and experimenting with parameters, I was able to match the results of the two models: 

```python
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.datasets import load_veterans_lung_cancer
from sksurv.preprocessing import OneHotEncoder

X_, y_ = load_veterans_lung_cancer()
X = OneHotEncoder().fit_transform(X_)

f = CoxPHSurvivalAnalysis(alpha=1, n_iter=100000)
g = CoxnetSurvivalAnalysis(alphas=[1/X.shape[0]], alpha_min_ratio=1, n_alphas=1, l1_ratio=1e-16, tol=1e-09, normalize=False)

print(f)
print(g)

f.fit(X, y_)
g.fit(X, y_)

print(f.coef_)
print(g.coef_[:,0])
print('Relative errors:\n', (f.coef_ - g.coef_[:,0]) / f.coef_)
```
Output:
```
CoxPHSurvivalAnalysis(alpha=1, n_iter=100000, tol=1e-09, verbose=0)
CoxnetSurvivalAnalysis(alpha_min_ratio=1, alphas=[0.0072992700729927005],
            copy_X=True, l1_ratio=1e-16, max_iter=100000, n_alphas=1,
            normalize=False, penalty_factor=None, tol=1e-09, verbose=False)
[-8.15647317e-03 -6.63327564e-01 -2.36950223e-01 -1.04657588e+00
 -3.26009359e-02 -2.71347095e-04  5.39815287e-02  2.89290932e-01]
[-8.15323389e-03 -6.63228135e-01 -2.36836564e-01 -1.04645919e+00
 -3.25993975e-02 -2.71575816e-04  5.39863418e-02  2.89279963e-01]
Relative errors:
 [ 3.97142155e-04  1.49894366e-04  4.79676516e-04  1.11497071e-04
  4.71911560e-05 -8.42911801e-04 -8.91616158e-05  3.79195919e-05]
```

This is reassuring.

**Comment by leihuang** [comment]
Now that the two models can give the same results, we can benchmark their performance and I find that `CoxnetSurvivalAnalysis` is about 35X faster than `CoxPHSurvivalAnalysis`. Given that `CoxnetSurvivalAnalysis` also implements a more general model (L1+L2 regularization), it makes sense to use it only for now, until one needs to dig into the details of the algorithm execution (where `CoxPHSurvivalAnalysis` provides better transparency).

**Comment by leihuang** [comment]
I think it makes sense to devote this issue to the different results between the two models, so I just changed the title back, and will close this thread now that it's resolved. Given that `CoxnetSurvivalAnalysis` seems a more desirable implementation as I concluded above, it is important to have those methods that are so far only available to `CoxPHSurvivalAnalysis` also available to `CoxnetSurvivalAnalysis`. I will open a different issue for that.

**Comment by pavopax** [comment]
Great work @leihuang !

**Comment by WellJoea** [comment]
So which coef was the best recommended  used for model？
the first one or the last one？
g.coef_[:,0] or g.coef_[:,-1]

**Comment by sebp** [comment]
It depends on your application really. Usually, you want to do
cross-validation to determine the optimal alpha and thus coefficients.
For an example, see e.g.
https://gist.github.com/sebp/d580d44c4beab3379c6dfda6810b33b8

**Comment by WellJoea** [comment]
I see. Thank you very much!
