### ISSUE TITLE
Question about what _get_survival_pairs() function does in NaiveSurvivalSVM

### ISSUE THREAD

**Issue by hermidalc** [sebp/scikit-survival#45]
The _get_survival_pairs() function in NaiveSurvivalSVM is really interesting because it seems to convert the X data and y structured array into X_pairs and y_pairs that are suitable for running with a classification algorithm, in this case LinearSVC.  

May I ask what kind of transformations is it doing to make this possible?  Using the veterans dataset, it looks like the number of samples increase by a lot when running _get_survival_pairs()
```
X.shape
(137, 8)
y.shape
(137,)
X_pairs.shape
(8843, 8)
y_pairs.shape
(8843,)
```

**Comment by sebp** [comment]
Please check the paper [Fast Training of Support Vector Machines for Survival Analysis](http://link.springer.com/chapter/10.1007/978-3-319-23525-7_15) for details.
