### ISSUE TITLE
Randomized Search CV for RSF Hyperparametertuning?

### ISSUE THREAD

**Issue by Bylandt** [sebp/scikit-survival#463]
Maybe a stupid question, and let me say i am sorry in advance.:

I am currently trying to establish a script for analysis of a larger dataset and am looking for a way to perform Hyperparametertuning using RandomizedSearchCV() instead of GridSearch, since the computation time gets too high for my purposes. 

Is there a way to use any of the as_concordance_index_ipcw_scorer(), as_cumulative_dynamic_auc_scorer(), as_integrated_brier_score_scorer() methods for scoring when performing hyerparametertuning using RandomizedSearchCV?

Many thanks and Kind regards,
B.

**Comment by sebp** [comment]
You should be able to use RandomizedSearchCV() in the same way as s 
GridSearchCV() described in 
https://scikit-survival.readthedocs.io/en/latest/user_guide/evaluating-survival-models.html#Using-Metrics-in-Hyper-parameter-Search
