### ISSUE TITLE
Dealing with left-censored or interval-censored data.

### ISSUE THREAD

**Issue by tpnk-dev** [sebp/scikit-survival#468]
I'm still unsure if I can work with left-censored or interval-censored data in scikit-survival. That is, for some instances, I know that the event of interest (death) happened between a lower bound and an upper bound, but I don't know its exact time. How would the values of "status" and "survival_in_days" be for these examples?

**Comment by sebp** [comment]
Currently, only right-censored data is supported. There are no plans to add support for left- or interval-censoring in the near future.
