### ISSUE TITLE
Time-varying Covariates

### ISSUE THREAD

**Issue by Vuong-Chu** [sebp/scikit-survival#477]
I see that time-varying survival regression is very popular. I would like to know if there are any functions in scikit-survival that can help me with it. Thanks.

**Comment by valmunos** [comment]
Hi, why was this marked as completed?  I am also curious about this issue.  Thanks.

**Comment by Vuong-Chu** [comment]
Hi, 

Scikit-survival does not support the time-varying variables. See this discussion: https://github.com/sebp/scikit-survival/issues/8

So, I found it in another package: https://lifelines.readthedocs.io/en/latest/Time%20varying%20survival%20regression.html
