### ISSUE TITLE
brier_score fails when there is a test time greater than a training time

### ISSUE THREAD

**Issue by dpellow** [sebp/scikit-survival#478]
brier_score() line 619 raises a ValueError with message 'time must be smaller than largest observed time point:' even when all of the time points in "times" are within the range of the test data. This occurs if the test data has a time point outside of the range of the training data, although that is not the documented behaviour

**Comment by sebp** [comment]
Can you please provide a minimal, reproducible example illustrating the 
problem you are experiencing?

See https://stackoverflow.com/help/minimal-reproducible-example for help 
to create such an example.

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.

**Comment by aliciaolivaresgil** [comment]
I have the same issue with "cumultaive_dynamic_auc". The documentation sais that time points in "times" must be within the range of times in "survival_test", but says nothing about times in "survival_test" being within the range of times in "survival_train". In fact, this happens in many examples and no error occurs. 

Here I leave a reproducible example where this error happens (sksurv version 0.22.2): https://github.com/aliciaolivaresgil/Reproduce_errors/blob/main/Error_example.ipynb
