### ISSUE TITLE
Get coefficients of CoxnetSurvivalAnalysis after GridSearchCV

### ISSUE THREAD

**Issue by JW3603** [sebp/scikit-survival#482]
Looks like I cannot use coef_ to get the best model's coefficients after GridSearchCV on CoxnetSurvivalAnalysis  

````
cph = CoxnetSurvivalAnalysis(fit_baseline_model=True)

lower, upper = np.percentile(df_y["LIFETIME"], [10, 90])
times = np.arange(lower, upper + 1)

grid_search = GridSearchCV(as_integrated_brier_score_scorer(cph, times=times),
                           param_grid=param_grid,
                           cv=cv,
                           n_jobs=-1,
                           return_train_score=True).fit(X_train_tf, y_train)

best_cph = grid_search.best_estimator_
coefficients = best_cph.coef_
````

SYSTEM
------
Platform          : Linux-5.10.225-213.878.amzn2.x86_64-x86_64-with-glibc2.35
Python version    : CPython <module 'platform' from '/opt/conda/lib/python3.10/platform.py'>
Python interpreter: /opt/conda/bin/python

DEPENDENCIES
------------
scikit-survival   : 0.23.0
scikit-learn      : 1.4.2
numpy             : 1.26.4
scipy             : 1.13.0
pandas            : 2.2.2
numexpr           : 2.9.0
ecos              : 2.0.14
osqp              : 0.6.7.post1
joblib            : 1.4.0
matplotlib        : 3.8.4
pytest            : 8.1.1
sphinx            : 7.2.6
Cython            : None
pip               : 24.0
setuptools        : 69.5.1

**Comment by sebp** [comment]
Thanks for reporting this issue.

Can you please provide the error message you are getting when executing your code?

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.
