### ISSUE TITLE
ExtraSurvivalTrees missing score method since 0.23

### ISSUE THREAD

**Issue by joshuafalter** [sebp/scikit-survival#487]
I'm not sure if this is a bug, but it appears the ExtraSurvivalTrees class is missing the score method since 0.23. I can see it was available in the 0.22 release here:https://scikit-survival.readthedocs.io/en/v0.22.0/api/generated/sksurv.ensemble.ExtraSurvivalTrees.html#sksurv.ensemble.ExtraSurvivalTrees but it is not available in 0.23 and I get an error when I try to call it now.

Is there a reason it's been removed? If so, is there an alternative way we should be calculating the C-index score of our predictions with the ExtraSurvivalTrees?  

Thank you!

**Comment by sebp** [comment]
Thanks for reporting this issue. This is indeed an unintended change.
