### ISSUE TITLE
Add Kaplan-Meier estimator for competing risks.

### ISSUE THREAD

**Issue by mvlvrd** [sebp/scikit-survival#490]
**Is your feature request related to a problem? Please describe.**
I would like to include a Kaplan-Meier estimator (cumulative incidences) for the case of competing risks.

**Describe the solution you'd like**
I have already written Python code for it. I am able to reproduce the results of [Scrucca et al.](https://pubmed.ncbi.nlm.nih.gov/17563735/) that follow the cmprsk R package. However, I have still some discrepancies for the confidence interval calculations.
I could send a pull request depending on how serious you consider the issue with the CI. (The differences are 5% for the test data set from Scrucca.)

**Describe alternatives you've considered**
The differences with the cmprsk implementation come from the variance estimators. I have actually implemented them using two formulas (Scrucca papers above) and the equivalent from [Choudhury](https://onlinelibrary.wiley.com/doi/10.1002/sim.1070) and get the same results, but I'm still unable to reproduce the results from the Fortran code in cmprsk.

**References and existing implementations**
https://luca-scr.github.io/software/#competing-risks-analysis
https://cran.r-project.org/web/packages/cmprsk/index.html

**Comment by sebp** [comment]
Thanks for helping to improve scikit-survival.

I'm not an expert in competing risks analysis, but I'd be happy to take a look at the code if you open a pull request.

**Comment by mvlvrd** [comment]
Thanks!
To be safe I will make a PR for code without the Confidence Interval.
