### ISSUE TITLE
"sksurv/linear_model/src/coxnet/coxnet.h:18:10: fatal error: Eigen/Core: No such file or directory" when compiling scikit-survival from source

### ISSUE THREAD

**Issue by hermidalc** [sebp/scikit-survival#51]
I was following instructions to install scikit-survival from source (because I want to use it with scikit-learn 0.20.0) and ran into the following error when running python setup.py install after creating sksurv environment and dependencies and activating it.
```bash
In file included from sksurv/linear_model/src/coxnet_wrapper.h:18,
                 from sksurv/linear_model/_coxnet.cpp:656:
sksurv/linear_model/src/coxnet/coxnet.h:18:10: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
          ^~~~~~~~~~~~
compilation terminated.
```
Looks like a missing dependency?

**Comment by sebp** [comment]
When using a git checkout, you need to initialize submodules: `git submodule update --init`. I should add this to the README

**Comment by hermidalc** [comment]
It works and compiles successfully now, thank you!
