### ISSUE TITLE
Make the datasets consistent

### ISSUE THREAD

**Issue by KOLANICH** [sebp/scikit-survival#55]
Some datasets cointn a boolean var indicating that an event has occured, in another ones that var means that event has not occured.

I think a dev shouldn't be forced to examine each dataset manually and write code specific to each dataset.

**Comment by sebp** [comment]
For each dataset, there's a [separate function](https://scikit-survival.readthedocs.io/en/latest/api.html#datasets) that loads the data and returns the event indicator as boolean.

**Comment by KOLANICH** [comment]
>For each dataset, there's a separate function that loads the data

I know, but they have problems.

>and returns the event indicator as boolean.

That event indicator in differrent datasets means opposite things, so I cannot just load the dataset, I have to load a dataset, examine its description, sum event column and check if the resulting value matches the one stated in the description as count of cases where events have occured.

**Comment by sebp** [comment]
A `False` in the event indicator always indicates right censoring and `True` an observed event. Could you please give an example where this does not hold? Obviously, the type of event differs among datasets.
