### ISSUE TITLE
Package imports error in SVM survival model

### ISSUE THREAD

**Issue by bacumin** [sebp/scikit-survival#6]
This might be specific to my package configuration, but when I try to run "from sksurv.svm import survival_svm", I get an import error in the survival_svm.py file "ImportError: No module named 'sksurv.svm._prsvm' , with the error coming from the line "from .survival_svm import FastKernelSurvivalSVM, FastSurvivalSVM" in the __init__.py file of the same directory.

**Comment by sebp** [comment]
`sksurv.svm._prsvm` is a C module that needs to be compiled, so I guess you haven't run `python setup.py install` or `python setup.py build_ext --inplace` (if you don't want to install it)?

**Comment by bacumin** [comment]
I compiled the files, but still get "Python 3.5 ImportError: dynamic module does not define module export function (PyInit__prsvm)", which comes from this line: "from ._prsvm import survival_constraints_simple, survival_constraints_with_support_vectors" in survival_svm.py.

**Comment by sebp** [comment]
Could you please check the contents of `<path to python>/site-packages/sksurv/svm` folder, which should contain something similar to `_prsvm.cpython-35m-darwin.so` (this is on a mac).

If there is no such file, please post the output of `python setup.py install` and the full versions of python, setuptools and numpy you are using.

**Comment by bacumin** [comment]
I found the bug - I was installing it into the wrong virtual env. My mistake, thanks for your help!

**Comment by Yuren-Zhong** [comment]
I tried to install it via Anaconda. It seems that those C files will not be compiled automatically
