### ISSUE TITLE
Calculating confidence intervals for coefficients

### ISSUE THREAD

**Issue by jim-rafferty** [sebp/scikit-survival#61]
Is it possible to calculate standard errors or confidence intervals for individual log coefficients in Cox / AFT models? If not, I think it would be a useful enhancement.

See https://stackoverflow.com/questions/55747022/calculating-confidence-intervals-for-coefficients-in-scikit-survival for code examples of what I'm talking about.

Thanks. :)

**Comment by sebp** [comment]
Confidence intervals usually only make sense when using no regularization, i.e. setting `alpha=0` for `CoxPHSurvivalAnalysis`. Therefore, I would find it confusing when the API would offer a function that can only be used in a special case. In addition, confidence intervals do not benefit the actual prediction, they just allow better interpretation of a fitted model. As the stackoverflow post mentions, lifelines already supports confidence intervals, therefore I'm inclined to not add it to scikit-survival.

**Comment by jim-rafferty** [comment]
This choice makes scikit-survival essentially unusable for most statistical work.

**Comment by hermidalc** [comment]
@sebp that makes sense to me, may I ask does this also apply to CoxPH coefficient p-values? That providing p-values only makes sense with `alpha=0` no ridge regression penalty.
