### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'fit_baseline_model'

### ISSUE THREAD

**Issue by phuongpm241** [sebp/scikit-survival#63]
I am trying to fit a CoxnetSurvivalAnalysis using this line:
`CoxnetSurvivalAnalysis(alpha_min_ratio = 0.01, l1_ratio=1, fit_baseline_model=True)`
but instead got an error:
`TypeError: __init__() got an unexpected keyword argument 'fit_baseline_model'`
I just recently installed sksurv using pip on a ubuntu machine. Was that feature deprecated? My sksurv version is 0.7

Thank you!

**Comment by phuongpm241** [comment]
Found an answer[ here.](https://github.com/sebp/scikit-survival/blob/0768703f8cad1aeb846477235edcc0124c7dbd28/doc/understanding_predictions.rst)

**Comment by sebp** [comment]
``fit_baseline_model`` has been added after 0.7 was released and is only available when installing from git master at the moment.
