### ISSUE TITLE
Literature for the accelerated failure time model

### ISSUE THREAD

**Issue by cristobaltapia** [sebp/scikit-survival#65]
Hi! First of all, thanks for writing this library! Reading through the code has helped me better understand the concepts present in different papers (statistical papers can be a bit confusing sometimes for outsiders :P ).

I have been reading about censored regression models for the last couple of weeks, because I want to use it with my data. After some research I think that the Accelerated failure time model is a good option for me. I found some good literature about it, for example [1]. But in that paper it is stated that "owing to the presence of censoring, usually the intercept parameter cannot be estimated well". However, the implementation of the class `IPCRidge()` considers a model with an intercept `\beta_0`. Could you provide some literature for this specific model, please? Maybe it would be a good idea to list it direct in the code, as done in other models.

Thanks!

[1] Wei, L. J. (1992), The accelerated failure time model: A useful alternative to the cox regression model in survival analysis. Statist. Med., 11: 1871-1879. doi:10.1002/sim.4780111409

**Comment by sebp** [comment]
The relevant reference for `IPCRidge` is
```
W. Stute, “Consistent estimation under random censorship when covariables are
present,” Journal of Multivariate Analysis, vol. 45, no. 1, pp. 89–103, 1993. doi:
10.1006/jmva.1993.1028.
```
There are many different forms of AFT models. I have to admit that I've chosen this one more for ease of implementation rather than statistical merits.

**Comment by cristobaltapia** [comment]
Thanks! I am also trying the WeibullAFTModel from the `lifetimes` library, and the results are at least very similar.
