### ISSUE TITLE
cancel the limit packages version  of sklearn, pandas and numy 

### ISSUE THREAD

**Issue by WellJoea** [sebp/scikit-survival#69]
I have installed the  lastest version of the sklearn, pandas and numy pacakges.
However, when i installed the scikit-survival, some packages reduce the vesion to specified that I cannot use for others software.

In the next vesion, could you  remove the cap of those  packages version?

Thank you very much!

**Comment by sebp** [comment]
Could you please list the packages that are down-graded?

**Comment by WellJoea** [comment]
Very thanks for your reply！！
First，  when I was installing the scikit-survival  package with 'pip install scikit-survival ', the problems that may arise were as follows:

1: UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1737: illegal multibyte sequence.
    This was coused by the  line  18  in the script setup.py, which was written as
     'with open('README.rst', ) as fp' . I think it is better using 'with open('README.rst', encoding='utf-8') as fp'

2.  The requirements files 'requirements/prod.txt'  needs the packages vesion to be satisfied as  follaws:
   pandas >=0.20,<0.24
   scipy >=1.0,<1.3.0
   scikit-learn >=0.19.0,<0.21
  
   Could you remove the cap of those packages version?
   such as ：
       pandas >=0.20
       scipy >=1.0
       scikit-learn >=0.19.0

Second. I read a paper, may be an oldfashion,  which is 'Penalized Cox Regression Analysis in the High-Dimensional and Low-sample Size Settings, with Applications to Mi-croarray Gene Expression Data'.
This paper was used for LARS-Lasso estimator in the special data（igh-Dimensional and Low-sample）.

Could you add this module in the scikit-survival ? 
I just give a little idea. You can ignore it.

Anyway, I always think the scikit-survival is the best packages usring for  survival analysis, which is better than the lifelines.


Think you very much！！

**Comment by sebp** [comment]
Unfortunately, the version caps are strictly required as pandas and scikit-learn do not always preserve backwards compatibility. In the case of scipy, 1.3.0 has a bug, which should be fixed in 1.3.1, once it is released.

The Cox-LASSO has been implemented in [CoxnetSurvivalAnalysis](https://scikit-survival.readthedocs.io/en/latest/generated/sksurv.linear_model.CoxnetSurvivalAnalysis.html#sksurv.linear_model.CoxnetSurvivalAnalysis).
