### ISSUE TITLE
Remove call of deprecated pandas API: Categorical.from_array

### ISSUE THREAD

**Issue by sebp** [sebp/scikit-survival#7]
`_get_dummies_1d` in [column.py](/sebp/scikit-survival/tree/master/sksurv/column.py) calls `Categorical.from_array`, which has been deprecated since pandas 0.19 (pandas-dev/pandas!13854):

```
sksurv/column.py:147: FutureWarning: Categorical.from_array is deprecated, use Categorical instead
  cat = pandas.Categorical.from_array(pandas.Series(data))
```

**Comment by scienceaiden** [comment]
simple replace     cat = pandas.Categorical.from_array(pandas.Series(data))  with 
    cat = pandas.Categorical(pandas.Series(data))  in column.py
