### ISSUE TITLE
ValueError: censoring survival function is zero at one or more time points

### ISSUE THREAD

**Issue by WellJoea** [sebp/scikit-survival#73]
Ghat = self.predict_proba(time[event])..    
if (Ghat == 0.0).any():        
    raise ValueError("censoring survival function is zero at one or more time points")    
the Ghat is:
[1.         0.99382716 0.         0.99382716 1.         0.99382716
 1.         0.99382716 0.36022332 0.99382716 0.99382716 0.99382716
 0.99382716 0.99382716 0.91355618 0.87939543 0.33770937 0.99382716
 0.99382716 0.89663847 0.80829537 0.99382716 0.99382716 0.97942387
 0.99382716 0.99382716 0.89663847 1.         0.99382716 0.99382716
 0.99382716 0.99382716 0.84421961 0.80829537 0.89663847 0.87939543
 0.99382716 1.         0.17729742]

I have limted the X_test time range in the range of  X_train between min and max.
But the fuction predict_ipcw got the ValueError resulted for  the 0 value in Ghat variable in the predict_ipcw function

**Comment by sebp** [comment]
Choosing min and max is problematic, because the IPCW estimate will be
zero if the first/last time point in the data is uncensored. It is
better to choose start and end time intervals with some distance, e.g.
using 10% and 90% percentile of all survival times.

**Comment by WellJoea** [comment]
I got it.
Thank very much.
