### ISSUE TITLE
Explain meaning of predictions of boosting models in API doc

### ISSUE THREAD

**Issue by peiyaoli** [sebp/scikit-survival#75]
Hi, @sebp 

In my project, I am building a survival prediction model. One of target model is XGBoost with Cox as objectives. Baseline model would be multivariate Cox regression. Is the prediction output same here? It looks like output from XGBoost is HR ratio. 

Best
Peiyao

**Comment by sebp** [comment]
For sksurv, predictions are the equivalent to the linear predictor of the traditional Cox model, thus can be interpreted as log hazard ratio.
