### ISSUE TITLE
AttributeError: 'CoxPHSurvivalAnalysis' object has no attribute 'baseline_survival_'

### ISSUE THREAD

**Issue by rebeccasartobasso** [sebp/scikit-survival#76]
When I print out the attributes of CoxPHSurvivalAnalysis neither 'baseline_survival_' or 'cum_baseline_hazard_' are there but they are listed as attributes in the documentation. Any chance you could fix this? Thanks! 
sksurv version: 0.8, sklearn version: 0.20.3

**Comment by sebp** [comment]
Good catch, this regression was introduced in commit
23fe263e110c7abb68099b48de3a06079e1e6cda.

**Comment by rebeccasartobasso** [comment]
I upgraded to sksurv 0.9 but still having problems. The commit you sent in previous comment is for CoxnetSurvivalAnalysis but I'm using CoxPHSurvivalAnalysis. Are 'baseline_survival_' and 'cum_baseline_hazard_' available for CoxPHSurvivalAnalysis as described in the documentation?
I get en error when I try to set "fit_baseline_model = True" for CoxPHSurvivalAnalysis:
__init__() got an unexpected keyword argument 'fit_baseline_model'
Let me know and thank you!

**Comment by sebp** [comment]
The fix is currently only available in git master. You'd need to install
the development version from git, or wait for the next release.
