### ISSUE TITLE
Clarify documentation for Gradient Boosted Regression Trees

### ISSUE THREAD

**Issue by gkaissis** [sebp/scikit-survival#77]
The ```subsample```parameter in ```sksurv.ensemble.GradientBoostingSurvivalAnalysis```reads under subsample:

_The fraction of samples to be used for fitting the individual base learners. If smaller than 1.0 this results in Stochastic Gradient Boosting._

It might be of benefit to clarify that the base learner is a regression tree and not a random forest, hence setting to values <1.0 this is equivalent to a non-bootstrapped RF. 

Or am I misunderstanding the documentation?

Cheers.

**Comment by sebp** [comment]
Why would you assume that base learners are random forests?

**Comment by gkaissis** [comment]
I would not, however there is no indication to the contrary. 

> Explicit is better than implicit.

**Comment by sebp** [comment]
Would you be able to create a pull request that includes the changes to
the API documentation?

**Comment by gkaissis** [comment]
Done. Didn't find any PR guidelines so I kept edits to a minimum. Please let me know if you need any modifications.
Cheers!
