### ISSUE TITLE
How can I get predictions for the exact time?

### ISSUE THREAD

**Issue by willthd** [sebp/scikit-survival#84]
I'm using SurvivalGradientBoosting from sksurv library.
And I want to get predictions for the exact time(like in 100 days, 365 days).
But model.predict method only needs just one parameter for data set.
In this case, What should i do?

**Comment by sebp** [comment]
I'm assuming you are referring to `GradientBoostingSurvivalAnalysis`. This particular model does not estimate time directly, but the relative order of events, see [the documentation](https://scikit-survival.readthedocs.io/en/latest/understanding_predictions.html#predictions) for more details. 
Issue #22 is related to what you may want, but this is not implement yet.
