### ISSUE TITLE
Install scikit-survival problem

### ISSUE THREAD

**Issue by luoshuangyang** [sebp/scikit-survival#87]
hi
When I installed scikit-survival on windows7, it showed No module named 'numpy.distutils._msvccompiler' in numpy.distutils;Trying the from distutils
Customize MSVCCompiler
Customize MSVCCompiler using build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils;Trying the from distutils
Customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
......
Error: Microsoft Visual c + + 14.0 is required. The Get it with "Build Tools for Visual Studio" : https://visualstudio.microsoft.com/downloads/, but the computer has been installed with Microsoft Visual c + + 14.0, someone encountered this problem?What should I do?thank you

**Comment by sebp** [comment]
I haven't encountered this particular problem, but Visual Studio needs to match the version Python was compiled with, see https://wiki.python.org/moin/WindowsCompilers

That said, I highly recommend to install the pre-built Anaconda packages.
