### ISSUE TITLE
Random forest logrank splitting decision rule

### ISSUE THREAD

**Issue by CamilaFernandez8** [sebp/scikit-survival#92]
Hello!
Is there any documentation on this topic? Why to pick logrank to measure the quality of a split?
Thanks!

Camila F

**Comment by sebp** [comment]
Log-rank splitting is most common splitting rule and is also used in the original random survival forest paper.

> Ishwaran, H., Kogalur, U. B., Blackstone, E. H., & Lauer, M. S. (2008). Random survival forests. The Annals of Applied Statistics, 2(3), 841–860. https://doi.org/10.1214/08-AOAS169
