### ISSUE TITLE
What is the origin of time for predict function?

### ISSUE THREAD

**Issue by mateuszbuda** [sebp/scikit-survival#94]
Based on the docs:

> If samples are ordered according to their predicted risk score (in ascending order), one obtains the sequence of events, as predicted by the model. This is the return value of the predict() method of all survival models in scikit-survival.

In my use case I need to predict the order in which individuals will die (in absolute/global time frame) given that they survived till the end (last day) of study.
I interpret predicted risk scores (using `predict()` function) as relative time to events.
However, it's not clear to me what is the origin of time for them?
Is it the time of birth for each individual (which would require adjusting risk scores in my use case), or is it the end of study time?

**Comment by poganyg** [comment]
From my understanding the risk scores are inversely related to the time-to-events. The model assigns risk scores to patients (predictions) and if it is working well then a patient with a higher risk score should have a lower time-to-event (which is essentially the label).

The time-to-event will be defined by your dataset I imagine. If your use-case is a clinical study, then the time-to-event will likely be the time from the beginning of the study until an event or censoring. 

I don't think that this implementation is returning anything involving time, only risk factors.

**Comment by sebp** [comment]
It is correct that the predict function only returns risk factors, which 
are not related to time in absolute terms. You would need to call 
predict_cumulative_hazard_function or predict_survival_function to 
obtain estimated over time (for those models that support it).

Also make sure you read the relevant part of the documentation:
https://scikit-survival.readthedocs.io/en/latest/understanding_predictions.html

**Comment by konradsemsch** [comment]
@sebp - isn't there any way to get from the output of `predict` to an expected lifetime value? Assuming one knows the survival curve for a given dataset? The lifetime probably cannot be inferred by normalising the score to the min/ max value from the survival curve?

**Comment by sebp** [comment]
@konradsemsch It's not implemented yet, but #190 discusses how this could be done.
