### ISSUE TITLE
Using IPCRidge aft model

### ISSUE THREAD

**Issue by jgrinaveckis** [sebp/scikit-survival#95]
Hello,

Not actually an issue, more like a question - as I'm using IPCRidge to model my survival data, I'm getting "strange" c-index results - it's only ~0.12. For example when using lifelines AFT model (Weibull for this example) I get score 0.91. Other models, which do not necessary fit my survival data got similar results, but nowhere near low as here. Is there some additional knowledge to retrieve when using this model?

Many thanks for answer!

**Comment by sebp** [comment]
In contrast to most other models, IPCRidge does not return a risk score, 
but the predicted (log) time of survival. Since 
concordance_index_censored expects a risk score, you would need to pass 
it the negative predicted log time or some other conversion to the risk 
score scale.
