### ISSUE TITLE
Mistake in the documentation of `concordance_index_censored` 

### ISSUE THREAD

**Issue by poganyg** [sebp/scikit-survival#96]
> Samples are comparable if for at least one of them an event occurred. If the estimated risk is larger for the sample with a higher time of event/censoring, the predictions of that pair are said to be concordant. 

In my understanding if the estimated risk is higher for A than for B then, for concordancy, the time-to-event should lower for A than for B. 

The first sentence is not completely correct either, there can be cases when an event occurred but the two individuals are still not comaprable, but you elaborate on this later in the paragraph, so it is not a big issue.

**Comment by sebp** [comment]
I can see that this is not entirely correct. If you could submit a merge 
request that clarifies this part, that would be very helpful.

**Comment by poganyg** [comment]
I am sorry, but I am really unsure how to submit a merge request for a doc file (which I can't find in this repo in the first place), so I'll paste here an updated version of the description, feel free to include it in the docs if you are happy with it.

---

Concordance index for right-censored data

The concordance index is defined as the proportion of all comparable pairs in which the predictions and outcomes are concordant.

Two samples are comparable if either both of them experienced an event (at different timepoints), or, if the one with a shorter observed survival time experienced an event, in which case it is said that the event free subject *outlived* the other. A pair is not comparable, if they experienced events at the same time.
Concordance intuitively means that two samples were ordered correctly by the model. More specifically, two samples are concordant, if the one with a higher estimated risk score is associated with a shorter survival time. When predicted risks are identical for a pair, 0.5 rather than 1 is added to the count of concordant pairs.

---
