### ISSUE TITLE
Survival random forest ImportError

### ISSUE THREAD

**Issue by Laolga** [sebp/scikit-survival#97]
Hi!
Trying to import survival random forest with:

`from sksurv.ensemble import RandomSurvivalForest`

But getting import error. Other models (FastSurvivalSVM, IPCRidge, etc) work fine.
Any suggestion on what I might be doing wrong?

Olga

**Comment by sebp** [comment]
Sounds like you have an older version, which did not include random 
survival forest yet. Can you please post the output of

```
import sksurv
print(sksurv.__version__)
```

**Comment by Laolga** [comment]
That's right, the version was 0.10
Thanks!
